// godot/godot.odin -- Public convenience facade.
//
// Prefer this package for normal extension code. It re-exports the stable core
// value helpers plus the selected generated builtin, utility, and class APIs.
// Manual class registration still uses some low-level core declarations until
// the Priority 3 registration helpers exist.
package godot

import gbind "godot:bindings"
import gbind_builtin "godot:bindings/builtin"
import gclass "godot:bindings/classes"
import gcore "godot:core"

// --- Core types ---
Object :: gcore.Object
RefCounted :: gcore.RefCounted
ObjectPtr :: gcore.ObjectPtr
ClassInstancePtr :: gcore.ClassInstancePtr
ConstStringNamePtr :: gcore.ConstStringNamePtr
ClassCreateInstance :: gcore.ClassCreateInstance
ClassFreeInstance :: gcore.ClassFreeInstance
ClassNotification :: gcore.ClassNotification
VariantStorage :: gcore.VariantStorage
Variant :: gcore.Variant
StringStorage :: gcore.StringStorage
String :: gcore.String
StringNameStorage :: gcore.StringNameStorage
StringName :: gcore.StringName
StaticStringName :: gcore.StaticStringName
ClassName :: gcore.ClassName
NodePathStorage :: gcore.NodePathStorage
NodePath :: gcore.NodePath
RIDStorage :: gcore.RIDStorage
RID :: gcore.RID
ArrayStorage :: gcore.ArrayStorage
Array :: gcore.Array
DictionaryStorage :: gcore.DictionaryStorage
Dictionary :: gcore.Dictionary
PackedByteArrayStorage :: gcore.PackedByteArrayStorage
PackedByteArray :: gcore.PackedByteArray
PackedInt32ArrayStorage :: gcore.PackedInt32ArrayStorage
PackedInt32Array :: gcore.PackedInt32Array
PackedInt64ArrayStorage :: gcore.PackedInt64ArrayStorage
PackedInt64Array :: gcore.PackedInt64Array
PackedFloat32ArrayStorage :: gcore.PackedFloat32ArrayStorage
PackedFloat32Array :: gcore.PackedFloat32Array
PackedFloat64ArrayStorage :: gcore.PackedFloat64ArrayStorage
PackedFloat64Array :: gcore.PackedFloat64Array
PackedStringArrayStorage :: gcore.PackedStringArrayStorage
PackedStringArray :: gcore.PackedStringArray
PackedVector2ArrayStorage :: gcore.PackedVector2ArrayStorage
PackedVector2Array :: gcore.PackedVector2Array
PackedVector3ArrayStorage :: gcore.PackedVector3ArrayStorage
PackedVector3Array :: gcore.PackedVector3Array
PackedVector4ArrayStorage :: gcore.PackedVector4ArrayStorage
PackedVector4Array :: gcore.PackedVector4Array
PackedColorArrayStorage :: gcore.PackedColorArrayStorage
PackedColorArray :: gcore.PackedColorArray
StringRepr :: gcore.StringRepr
GodotReal :: gcore.GodotReal
Vector2 :: gcore.Vector2
Vector3 :: gcore.Vector3
Vector4 :: gcore.Vector4
Color :: gcore.Color
Resource :: gclass.Resource
Node :: gclass.Node
CanvasItem :: gclass.CanvasItem
Node2D :: gclass.Node2D
Control :: gclass.Control

// --- Core functions ---
is_nil :: gcore.is_nil
is_class :: gcore.is_class
cast_to :: gcore.cast_to
init_class_casting :: gcore.init_class_casting
register_class_with_defaults :: gcore.register_class_with_defaults
unregister_class :: gcore.unregister_class
object_to_variant :: gcore.object_to_variant
object_from_variant :: gcore.object_from_variant
variant_try_object :: gcore.variant_try_object
godot_context :: gcore.godot_context
init_class_bindings :: gclass.init_class_bindings
ref_counted_as_object :: gclass.ref_counted_as_object
resource_as_ref_counted :: gclass.resource_as_ref_counted
resource_as_object :: gclass.resource_as_object
ref_counted_get_reference_count :: gclass.ref_counted_get_reference_count
resource_get_path :: gclass.resource_get_path
resource_get_rid :: gclass.resource_get_rid
resource_set_local_to_scene :: gclass.resource_set_local_to_scene
resource_is_local_to_scene :: gclass.resource_is_local_to_scene
node_as_object :: gclass.node_as_object
node_get_parent :: gclass.node_get_parent
node_is_ancestor_of :: gclass.node_is_ancestor_of
node_get_path_to :: gclass.node_get_path_to
canvas_item_set_visible :: gclass.canvas_item_set_visible
canvas_item_is_visible :: gclass.canvas_item_is_visible
canvas_item_show :: gclass.canvas_item_show
canvas_item_hide :: gclass.canvas_item_hide
canvas_item_queue_redraw :: gclass.canvas_item_queue_redraw
canvas_item_get_canvas :: gclass.canvas_item_get_canvas
canvas_item_as_node :: gclass.canvas_item_as_node
canvas_item_as_object :: gclass.canvas_item_as_object
node2d_as_canvas_item :: gclass.node2d_as_canvas_item
node2d_as_node :: gclass.node2d_as_node
node2d_as_object :: gclass.node2d_as_object
object_get_class :: gclass.object_get_class
object_is_class :: gclass.object_is_class
object_set_meta :: gclass.object_set_meta
object_get_meta :: gclass.object_get_meta
node2d_set_position :: gclass.node2d_set_position
node2d_get_position :: gclass.node2d_get_position
node2d_set_rotation :: gclass.node2d_set_rotation
node2d_get_rotation :: gclass.node2d_get_rotation
control_set_custom_minimum_size :: gclass.control_set_custom_minimum_size
control_get_custom_minimum_size :: gclass.control_get_custom_minimum_size
control_set_focus_mode :: gclass.control_set_focus_mode
control_get_focus_mode :: gclass.control_get_focus_mode
control_has_focus :: gclass.control_has_focus
control_grab_focus :: gclass.control_grab_focus
control_release_focus :: gclass.control_release_focus
control_set_mouse_filter :: gclass.control_set_mouse_filter
control_get_mouse_filter :: gclass.control_get_mouse_filter
control_as_canvas_item :: gclass.control_as_canvas_item
control_as_node :: gclass.control_as_node
control_as_object :: gclass.control_as_object
object_is_ref_counted :: gclass.object_is_ref_counted
object_try_as_ref_counted :: gclass.object_try_as_ref_counted
object_is_resource :: gclass.object_is_resource
object_try_as_resource :: gclass.object_try_as_resource
object_is_node :: gclass.object_is_node
object_try_as_node :: gclass.object_try_as_node
object_is_canvas_item :: gclass.object_is_canvas_item
object_try_as_canvas_item :: gclass.object_try_as_canvas_item
object_is_node2d :: gclass.object_is_node2d
object_try_as_node2d :: gclass.object_try_as_node2d
object_is_control :: gclass.object_is_control
object_try_as_control :: gclass.object_try_as_control
ref_counted_is_resource :: gclass.ref_counted_is_resource
ref_counted_try_as_resource :: gclass.ref_counted_try_as_resource
node_is_canvas_item :: gclass.node_is_canvas_item
node_try_as_canvas_item :: gclass.node_try_as_canvas_item
node_is_node2d :: gclass.node_is_node2d
node_try_as_node2d :: gclass.node_try_as_node2d
node_is_control :: gclass.node_is_control
node_try_as_control :: gclass.node_try_as_control
canvas_item_is_node2d :: gclass.canvas_item_is_node2d
canvas_item_try_as_node2d :: gclass.canvas_item_try_as_node2d
canvas_item_is_control :: gclass.canvas_item_is_control
canvas_item_try_as_control :: gclass.canvas_item_try_as_control

// --- Class enums and constants ---
ObjectConnectFlags :: gclass.ObjectConnectFlags
ResourceDeepDuplicateMode :: gclass.ResourceDeepDuplicateMode
NodeProcessMode :: gclass.NodeProcessMode
NodeProcessThreadGroup :: gclass.NodeProcessThreadGroup
NodeProcessThreadMessages :: gclass.NodeProcessThreadMessages
NodePhysicsInterpolationMode :: gclass.NodePhysicsInterpolationMode
NodeDuplicateFlags :: gclass.NodeDuplicateFlags
NodeInternalMode :: gclass.NodeInternalMode
NodeAutoTranslateMode :: gclass.NodeAutoTranslateMode
CanvasItemTextureFilter :: gclass.CanvasItemTextureFilter
CanvasItemTextureRepeat :: gclass.CanvasItemTextureRepeat
CanvasItemClipChildrenMode :: gclass.CanvasItemClipChildrenMode
CanvasItemOversamplingWithScale :: gclass.CanvasItemOversamplingWithScale
ControlFocusMode :: gclass.ControlFocusMode
ControlFocusBehaviorRecursive :: gclass.ControlFocusBehaviorRecursive
ControlMouseBehaviorRecursive :: gclass.ControlMouseBehaviorRecursive
ControlCursorShape :: gclass.ControlCursorShape
ControlLayoutPreset :: gclass.ControlLayoutPreset
ControlLayoutPresetMode :: gclass.ControlLayoutPresetMode
ControlSizeFlags :: gclass.ControlSizeFlags
ControlMouseFilter :: gclass.ControlMouseFilter
object_notification_postinitialize :: gclass.object_notification_postinitialize
object_notification_predelete :: gclass.object_notification_predelete
object_notification_extension_reloaded :: gclass.object_notification_extension_reloaded
node_notification_enter_tree :: gclass.node_notification_enter_tree
node_notification_exit_tree :: gclass.node_notification_exit_tree
node_notification_ready :: gclass.node_notification_ready
node_notification_process :: gclass.node_notification_process
node_notification_physics_process :: gclass.node_notification_physics_process
canvas_item_notification_draw :: gclass.canvas_item_notification_draw
canvas_item_notification_transform_changed :: gclass.canvas_item_notification_transform_changed
canvas_item_notification_visibility_changed :: gclass.canvas_item_notification_visibility_changed
control_notification_resized :: gclass.control_notification_resized
control_notification_focus_enter :: gclass.control_notification_focus_enter
control_notification_focus_exit :: gclass.control_notification_focus_exit
control_notification_theme_changed :: gclass.control_notification_theme_changed

// --- String ---
string_ptr :: gcore.string_ptr
const_string_ptr :: gcore.const_string_ptr
uninitialized_string_ptr :: gcore.uninitialized_string_ptr
string_init_utf8 :: gcore.string_init_utf8
string_from_utf8 :: gcore.string_from_utf8
string_utf8_len :: gcore.string_utf8_len
string_to_utf8 :: gcore.string_to_utf8
string_free :: gcore.string_free
string_length :: gcore.string_length
string_is_empty :: gcore.string_is_empty
string_hash :: gcore.string_hash
string_casecmp_to :: gcore.string_casecmp_to
string_nocasecmp_to :: gcore.string_nocasecmp_to
string_naturalcasecmp_to :: gcore.string_naturalcasecmp_to
string_naturalnocasecmp_to :: gcore.string_naturalnocasecmp_to
string_begins_with :: gcore.string_begins_with
string_ends_with :: gcore.string_ends_with
string_contains :: gcore.string_contains

// --- StringName ---
string_name_ptr :: gcore.string_name_ptr
const_string_name_ptr :: gcore.const_string_name_ptr
uninitialized_string_name_ptr :: gcore.uninitialized_string_name_ptr
string_name_init_utf8_cstring :: gcore.string_name_init_utf8_cstring
string_name_from_utf8_cstring :: gcore.string_name_from_utf8_cstring
string_name_free :: gcore.string_name_free
static_string_name_ptr :: gcore.static_string_name_ptr
const_static_string_name_ptr :: gcore.const_static_string_name_ptr
uninitialized_static_string_name_ptr :: gcore.uninitialized_static_string_name_ptr
static_string_name_init_latin1_cstring :: gcore.static_string_name_init_latin1_cstring
class_name_ptr :: gcore.class_name_ptr
class_name_init_latin1_cstring :: gcore.class_name_init_latin1_cstring

// --- NodePath ---
node_path_ptr :: gcore.node_path_ptr
const_node_path_ptr :: gcore.const_node_path_ptr
uninitialized_node_path_ptr :: gcore.uninitialized_node_path_ptr
node_path_init_from_string :: gcore.node_path_init_from_string
node_path_from_string :: gcore.node_path_from_string
node_path_init_utf8 :: gcore.node_path_init_utf8
node_path_from_utf8 :: gcore.node_path_from_utf8
node_path_init_copy :: gcore.node_path_init_copy
node_path_copy :: gcore.node_path_copy
node_path_free :: gcore.node_path_free
node_path_is_absolute :: gcore.node_path_is_absolute
node_path_get_name :: gcore.node_path_get_name
node_path_get_subname :: gcore.node_path_get_subname
node_path_get_concatenated_names :: gcore.node_path_get_concatenated_names
node_path_get_concatenated_subnames :: gcore.node_path_get_concatenated_subnames
node_path_get_name_count :: gcore.node_path_get_name_count
node_path_get_subname_count :: gcore.node_path_get_subname_count
node_path_hash :: gcore.node_path_hash

// --- RID ---
rid_ptr :: gcore.rid_ptr
const_rid_ptr :: gcore.const_rid_ptr
uninitialized_rid_ptr :: gcore.uninitialized_rid_ptr
rid_init_new :: gcore.rid_init_new
rid_new :: gcore.rid_new
rid_init_copy :: gcore.rid_init_copy
rid_copy :: gcore.rid_copy
rid_free :: gcore.rid_free
rid_is_valid :: gcore.rid_is_valid
rid_get_id :: gcore.rid_get_id

// --- Array ---
array_ptr :: gcore.array_ptr
const_array_ptr :: gcore.const_array_ptr
uninitialized_array_ptr :: gcore.uninitialized_array_ptr
array_init_new :: gcore.array_init_new
array_new :: gcore.array_new
array_init_copy :: gcore.array_init_copy
array_copy :: gcore.array_copy
array_free :: gcore.array_free
array_push :: gcore.array_push
array_size :: gcore.array_size
array_is_empty :: gcore.array_is_empty
array_clear :: gcore.array_clear
array_get :: gcore.array_get
array_set :: gcore.array_set
array_erase :: gcore.array_erase
array_has :: gcore.array_has

// --- Dictionary ---
dictionary_ptr :: gcore.dictionary_ptr
const_dictionary_ptr :: gcore.const_dictionary_ptr
uninitialized_dictionary_ptr :: gcore.uninitialized_dictionary_ptr
dictionary_init_new :: gcore.dictionary_init_new
dictionary_new :: gcore.dictionary_new
dictionary_init_copy :: gcore.dictionary_init_copy
dictionary_copy :: gcore.dictionary_copy
dictionary_free :: gcore.dictionary_free
dictionary_set :: gcore.dictionary_set
dictionary_has :: gcore.dictionary_has
dictionary_size :: gcore.dictionary_size
dictionary_is_empty :: gcore.dictionary_is_empty
dictionary_clear :: gcore.dictionary_clear
dictionary_erase :: gcore.dictionary_erase
dictionary_get_or_default :: gcore.dictionary_get_or_default
dictionary_get :: gcore.dictionary_get

// --- PackedByteArray ---
packed_byte_array_ptr :: gcore.packed_byte_array_ptr
const_packed_byte_array_ptr :: gcore.const_packed_byte_array_ptr
uninitialized_packed_byte_array_ptr :: gcore.uninitialized_packed_byte_array_ptr
packed_byte_array_init_new :: gcore.packed_byte_array_init_new
packed_byte_array_new :: gcore.packed_byte_array_new
packed_byte_array_init_copy :: gcore.packed_byte_array_init_copy
packed_byte_array_copy :: gcore.packed_byte_array_copy
packed_byte_array_free :: gcore.packed_byte_array_free
packed_byte_array_size :: gcore.packed_byte_array_size
packed_byte_array_is_empty :: gcore.packed_byte_array_is_empty
packed_byte_array_clear :: gcore.packed_byte_array_clear
packed_byte_array_get :: gcore.packed_byte_array_get
packed_byte_array_set :: gcore.packed_byte_array_set
packed_byte_array_push :: gcore.packed_byte_array_push

// --- PackedInt32Array ---
packed_int32_array_ptr :: gcore.packed_int32_array_ptr
const_packed_int32_array_ptr :: gcore.const_packed_int32_array_ptr
uninitialized_packed_int32_array_ptr :: gcore.uninitialized_packed_int32_array_ptr
packed_int32_array_init_new :: gcore.packed_int32_array_init_new
packed_int32_array_new :: gcore.packed_int32_array_new
packed_int32_array_init_copy :: gcore.packed_int32_array_init_copy
packed_int32_array_copy :: gcore.packed_int32_array_copy
packed_int32_array_free :: gcore.packed_int32_array_free
packed_int32_array_size :: gcore.packed_int32_array_size
packed_int32_array_is_empty :: gcore.packed_int32_array_is_empty
packed_int32_array_clear :: gcore.packed_int32_array_clear
packed_int32_array_get :: gcore.packed_int32_array_get
packed_int32_array_set :: gcore.packed_int32_array_set
packed_int32_array_push :: gcore.packed_int32_array_push

// --- PackedInt64Array ---
packed_int64_array_ptr :: gcore.packed_int64_array_ptr
const_packed_int64_array_ptr :: gcore.const_packed_int64_array_ptr
uninitialized_packed_int64_array_ptr :: gcore.uninitialized_packed_int64_array_ptr
packed_int64_array_init_new :: gcore.packed_int64_array_init_new
packed_int64_array_new :: gcore.packed_int64_array_new
packed_int64_array_init_copy :: gcore.packed_int64_array_init_copy
packed_int64_array_copy :: gcore.packed_int64_array_copy
packed_int64_array_free :: gcore.packed_int64_array_free
packed_int64_array_size :: gcore.packed_int64_array_size
packed_int64_array_is_empty :: gcore.packed_int64_array_is_empty
packed_int64_array_clear :: gcore.packed_int64_array_clear
packed_int64_array_get :: gcore.packed_int64_array_get
packed_int64_array_set :: gcore.packed_int64_array_set
packed_int64_array_push :: gcore.packed_int64_array_push

// --- PackedFloat32Array ---
packed_float32_array_ptr :: gcore.packed_float32_array_ptr
const_packed_float32_array_ptr :: gcore.const_packed_float32_array_ptr
uninitialized_packed_float32_array_ptr :: gcore.uninitialized_packed_float32_array_ptr
packed_float32_array_init_new :: gcore.packed_float32_array_init_new
packed_float32_array_new :: gcore.packed_float32_array_new
packed_float32_array_init_copy :: gcore.packed_float32_array_init_copy
packed_float32_array_copy :: gcore.packed_float32_array_copy
packed_float32_array_free :: gcore.packed_float32_array_free
packed_float32_array_size :: gcore.packed_float32_array_size
packed_float32_array_is_empty :: gcore.packed_float32_array_is_empty
packed_float32_array_clear :: gcore.packed_float32_array_clear
packed_float32_array_get :: gcore.packed_float32_array_get
packed_float32_array_set :: gcore.packed_float32_array_set
packed_float32_array_push :: gcore.packed_float32_array_push

// --- PackedFloat64Array ---
packed_float64_array_ptr :: gcore.packed_float64_array_ptr
const_packed_float64_array_ptr :: gcore.const_packed_float64_array_ptr
uninitialized_packed_float64_array_ptr :: gcore.uninitialized_packed_float64_array_ptr
packed_float64_array_init_new :: gcore.packed_float64_array_init_new
packed_float64_array_new :: gcore.packed_float64_array_new
packed_float64_array_init_copy :: gcore.packed_float64_array_init_copy
packed_float64_array_copy :: gcore.packed_float64_array_copy
packed_float64_array_free :: gcore.packed_float64_array_free
packed_float64_array_size :: gcore.packed_float64_array_size
packed_float64_array_is_empty :: gcore.packed_float64_array_is_empty
packed_float64_array_clear :: gcore.packed_float64_array_clear
packed_float64_array_get :: gcore.packed_float64_array_get
packed_float64_array_set :: gcore.packed_float64_array_set
packed_float64_array_push :: gcore.packed_float64_array_push

// --- PackedStringArray ---
packed_string_array_ptr :: gcore.packed_string_array_ptr
const_packed_string_array_ptr :: gcore.const_packed_string_array_ptr
uninitialized_packed_string_array_ptr :: gcore.uninitialized_packed_string_array_ptr
packed_string_array_init_new :: gcore.packed_string_array_init_new
packed_string_array_new :: gcore.packed_string_array_new
packed_string_array_init_copy :: gcore.packed_string_array_init_copy
packed_string_array_copy :: gcore.packed_string_array_copy
packed_string_array_free :: gcore.packed_string_array_free
packed_string_array_size :: gcore.packed_string_array_size
packed_string_array_is_empty :: gcore.packed_string_array_is_empty
packed_string_array_clear :: gcore.packed_string_array_clear
packed_string_array_get :: gcore.packed_string_array_get
packed_string_array_set :: gcore.packed_string_array_set
packed_string_array_push :: gcore.packed_string_array_push

// --- PackedVector2Array ---
packed_vector2_array_ptr :: gcore.packed_vector2_array_ptr
const_packed_vector2_array_ptr :: gcore.const_packed_vector2_array_ptr
uninitialized_packed_vector2_array_ptr :: gcore.uninitialized_packed_vector2_array_ptr
packed_vector2_array_init_new :: gcore.packed_vector2_array_init_new
packed_vector2_array_new :: gcore.packed_vector2_array_new
packed_vector2_array_init_copy :: gcore.packed_vector2_array_init_copy
packed_vector2_array_copy :: gcore.packed_vector2_array_copy
packed_vector2_array_free :: gcore.packed_vector2_array_free
packed_vector2_array_size :: gcore.packed_vector2_array_size
packed_vector2_array_is_empty :: gcore.packed_vector2_array_is_empty
packed_vector2_array_clear :: gcore.packed_vector2_array_clear
packed_vector2_array_get :: gcore.packed_vector2_array_get
packed_vector2_array_set :: gcore.packed_vector2_array_set
packed_vector2_array_push :: gcore.packed_vector2_array_push

// --- PackedVector3Array ---
packed_vector3_array_ptr :: gcore.packed_vector3_array_ptr
const_packed_vector3_array_ptr :: gcore.const_packed_vector3_array_ptr
uninitialized_packed_vector3_array_ptr :: gcore.uninitialized_packed_vector3_array_ptr
packed_vector3_array_init_new :: gcore.packed_vector3_array_init_new
packed_vector3_array_new :: gcore.packed_vector3_array_new
packed_vector3_array_init_copy :: gcore.packed_vector3_array_init_copy
packed_vector3_array_copy :: gcore.packed_vector3_array_copy
packed_vector3_array_free :: gcore.packed_vector3_array_free
packed_vector3_array_size :: gcore.packed_vector3_array_size
packed_vector3_array_is_empty :: gcore.packed_vector3_array_is_empty
packed_vector3_array_clear :: gcore.packed_vector3_array_clear
packed_vector3_array_get :: gcore.packed_vector3_array_get
packed_vector3_array_set :: gcore.packed_vector3_array_set
packed_vector3_array_push :: gcore.packed_vector3_array_push

// --- PackedVector4Array ---
packed_vector4_array_ptr :: gcore.packed_vector4_array_ptr
const_packed_vector4_array_ptr :: gcore.const_packed_vector4_array_ptr
uninitialized_packed_vector4_array_ptr :: gcore.uninitialized_packed_vector4_array_ptr
packed_vector4_array_init_new :: gcore.packed_vector4_array_init_new
packed_vector4_array_new :: gcore.packed_vector4_array_new
packed_vector4_array_init_copy :: gcore.packed_vector4_array_init_copy
packed_vector4_array_copy :: gcore.packed_vector4_array_copy
packed_vector4_array_free :: gcore.packed_vector4_array_free
packed_vector4_array_size :: gcore.packed_vector4_array_size
packed_vector4_array_is_empty :: gcore.packed_vector4_array_is_empty
packed_vector4_array_clear :: gcore.packed_vector4_array_clear
packed_vector4_array_get :: gcore.packed_vector4_array_get
packed_vector4_array_set :: gcore.packed_vector4_array_set
packed_vector4_array_push :: gcore.packed_vector4_array_push

// --- PackedColorArray ---
packed_color_array_ptr :: gcore.packed_color_array_ptr
const_packed_color_array_ptr :: gcore.const_packed_color_array_ptr
uninitialized_packed_color_array_ptr :: gcore.uninitialized_packed_color_array_ptr
packed_color_array_init_new :: gcore.packed_color_array_init_new
packed_color_array_new :: gcore.packed_color_array_new
packed_color_array_init_copy :: gcore.packed_color_array_init_copy
packed_color_array_copy :: gcore.packed_color_array_copy
packed_color_array_free :: gcore.packed_color_array_free
packed_color_array_size :: gcore.packed_color_array_size
packed_color_array_is_empty :: gcore.packed_color_array_is_empty
packed_color_array_clear :: gcore.packed_color_array_clear
packed_color_array_get :: gcore.packed_color_array_get
packed_color_array_set :: gcore.packed_color_array_set
packed_color_array_push :: gcore.packed_color_array_push

// --- Variant ---
variant_type :: gcore.variant_type
variant_is_type :: gcore.variant_is_type
variant_is_nil :: gcore.variant_is_nil
variant_ptr :: gcore.variant_ptr
const_variant_ptr :: gcore.const_variant_ptr
uninitialized_variant_ptr :: gcore.uninitialized_variant_ptr
variant_init_nil :: gcore.variant_init_nil
variant_nil :: gcore.variant_nil
variant_init_copy :: gcore.variant_init_copy
variant_copy :: gcore.variant_copy
variant_from_float :: gcore.variant_from_float
variant_from_int :: gcore.variant_from_int
variant_from_bool :: gcore.variant_from_bool
variant_from_string :: gcore.variant_from_string
variant_from_string_name :: gcore.variant_from_string_name
variant_from_node_path :: gcore.variant_from_node_path
variant_from_rid :: gcore.variant_from_rid
variant_from_array :: gcore.variant_from_array
variant_from_dictionary :: gcore.variant_from_dictionary
variant_from_packed_byte_array :: gcore.variant_from_packed_byte_array
variant_from_packed_int32_array :: gcore.variant_from_packed_int32_array
variant_from_packed_int64_array :: gcore.variant_from_packed_int64_array
variant_from_packed_float32_array :: gcore.variant_from_packed_float32_array
variant_from_packed_float64_array :: gcore.variant_from_packed_float64_array
variant_from_packed_string_array :: gcore.variant_from_packed_string_array
variant_from_packed_vector2_array :: gcore.variant_from_packed_vector2_array
variant_from_packed_vector3_array :: gcore.variant_from_packed_vector3_array
variant_from_packed_vector4_array :: gcore.variant_from_packed_vector4_array
variant_from_packed_color_array :: gcore.variant_from_packed_color_array
variant_from_utf8 :: gcore.variant_from_utf8
variant_from_cstring :: gcore.variant_from_cstring
variant_to_float :: gcore.variant_to_float
variant_to_int :: gcore.variant_to_int
variant_to_bool :: gcore.variant_to_bool
variant_to_string_storage :: gcore.variant_to_string_storage
variant_to_string :: gcore.variant_to_string
variant_try_string :: gcore.variant_try_string
variant_to_string_name :: gcore.variant_to_string_name
variant_try_string_name :: gcore.variant_try_string_name
variant_to_node_path :: gcore.variant_to_node_path
variant_try_node_path :: gcore.variant_try_node_path
variant_to_rid :: gcore.variant_to_rid
variant_try_rid :: gcore.variant_try_rid
variant_to_array :: gcore.variant_to_array
variant_try_array :: gcore.variant_try_array
variant_to_dictionary :: gcore.variant_to_dictionary
variant_try_dictionary :: gcore.variant_try_dictionary
variant_to_packed_byte_array :: gcore.variant_to_packed_byte_array
variant_try_packed_byte_array :: gcore.variant_try_packed_byte_array
variant_to_packed_int32_array :: gcore.variant_to_packed_int32_array
variant_try_packed_int32_array :: gcore.variant_try_packed_int32_array
variant_to_packed_int64_array :: gcore.variant_to_packed_int64_array
variant_try_packed_int64_array :: gcore.variant_try_packed_int64_array
variant_to_packed_float32_array :: gcore.variant_to_packed_float32_array
variant_try_packed_float32_array :: gcore.variant_try_packed_float32_array
variant_to_packed_float64_array :: gcore.variant_to_packed_float64_array
variant_try_packed_float64_array :: gcore.variant_try_packed_float64_array
variant_to_packed_string_array :: gcore.variant_to_packed_string_array
variant_try_packed_string_array :: gcore.variant_try_packed_string_array
variant_to_packed_vector2_array :: gcore.variant_to_packed_vector2_array
variant_try_packed_vector2_array :: gcore.variant_try_packed_vector2_array
variant_to_packed_vector3_array :: gcore.variant_to_packed_vector3_array
variant_try_packed_vector3_array :: gcore.variant_try_packed_vector3_array
variant_to_packed_vector4_array :: gcore.variant_to_packed_vector4_array
variant_try_packed_vector4_array :: gcore.variant_try_packed_vector4_array
variant_to_packed_color_array :: gcore.variant_to_packed_color_array
variant_try_packed_color_array :: gcore.variant_try_packed_color_array
variant_string_utf8_len :: gcore.variant_string_utf8_len
variant_try_utf8 :: gcore.variant_try_utf8
variant_try_float :: gcore.variant_try_float
variant_try_int :: gcore.variant_try_int
variant_try_bool :: gcore.variant_try_bool
variant_free :: gcore.variant_free
variant_free_temp :: gcore.variant_free_temp
call_error_ok :: gcore.call_error_ok
require_call_ok :: gcore.require_call_ok
variant_construct_checked :: gcore.variant_construct_checked
variant_call_checked :: gcore.variant_call_checked
print :: gcore.print
print_init :: gcore.print_init

// --- Generated builtin helpers used by the public facade smoke path ---
color_to_html :: gbind_builtin.color_to_html
color_html :: gbind_builtin.color_html
vector2_new3 :: gbind_builtin.vector2_new3
vector2_to_variant :: gbind_builtin.vector2_to_variant
vector2_try_from_variant :: gbind_builtin.vector2_try_from_variant
vector2_length :: gbind_builtin.vector2_length
vector2_normalized :: gbind_builtin.vector2_normalized
vector2_dot :: gbind_builtin.vector2_dot

// --- Utility functions ---
sin :: gbind.sin
cos :: gbind.cos
tan :: gbind.tan
randf :: gbind.randf
