// variant.odin — Variant marshaling and utility-function wrappers.
// These are manual prototypes; eventually they will be generated by godot-codegen.
// https://docs.godotengine.org/fr/4.x/classes/class_variant.html
package godot

import ffi "godot:godot-ffi"

GDExtensionVariant_Size :: 24

// ---- Variant construction ----

variant_from_float :: proc "contextless" (x: f64) -> (v: [GDExtensionVariant_Size]u8) {
	ctor := ffi.get_variant_from_type_constructor(.Float)
	_x := x
	ctor(cast(ffi.UninitializedVariantPtr)&v[0], cast(ffi.TypePtr)&_x)
	return
}

variant_from_cstring :: proc "contextless" (s: cstring) -> (v: [GDExtensionVariant_Size]u8) {
	str_data: [8]u8
	ffi.string_new_with_latin1_chars(cast(ffi.UninitializedStringPtr)&str_data[0], s)
	ctor := ffi.get_variant_from_type_constructor(.String)
	ctor(cast(ffi.UninitializedVariantPtr)&v[0], cast(ffi.TypePtr)&str_data[0])
	return
}

variant_free :: proc "contextless" (v: ^[GDExtensionVariant_Size]u8) {
	ffi.variant_destroy(cast(ffi.VariantPtr)&v[0])
}

variant_from_bool :: proc "contextless" (x: bool) -> (v: [GDExtensionVariant_Size]u8) {
	ctor := ffi.get_variant_from_type_constructor(.Bool)
	_x := x
	ctor(cast(ffi.UninitializedVariantPtr)&v[0], cast(ffi.TypePtr)&_x)
	return
}

variant_from_int :: proc "contextless" (x: i64) -> (v: [GDExtensionVariant_Size]u8) {
	ctor := ffi.get_variant_from_type_constructor(.Int)
	_x := x
	ctor(cast(ffi.UninitializedVariantPtr)&v[0], cast(ffi.TypePtr)&_x)
	return
}

// ---- Variant extraction ----

variant_to_float :: proc "contextless" (v: ^[GDExtensionVariant_Size]u8) -> f64 {
	ctor := ffi.get_variant_to_type_constructor(.Float)
	ret: f64
	ctor(cast(ffi.UninitializedTypePtr)&ret, cast(ffi.VariantPtr)&v[0])
	return ret
}

variant_to_int :: proc "contextless" (v: ^[GDExtensionVariant_Size]u8) -> i64 {
	ctor := ffi.get_variant_to_type_constructor(.Int)
	ret: i64
	ctor(cast(ffi.UninitializedTypePtr)&ret, cast(ffi.VariantPtr)&v[0])
	return ret
}

variant_to_bool :: proc "contextless" (v: ^[GDExtensionVariant_Size]u8) -> bool {
	ctor := ffi.get_variant_to_type_constructor(.Bool)
	ret: bool
	ctor(cast(ffi.UninitializedTypePtr)&ret, cast(ffi.VariantPtr)&v[0])
	return ret
}

// ---- Array builtin ----

array_new :: proc "contextless" () -> (v: [GDExtensionVariant_Size]u8) {
	err: ffi.CallError
	ffi.variant_construct(.Array, cast(ffi.UninitializedVariantPtr)&v[0], nil, 0, &err)
	return
}

array_push :: proc "contextless" (
	arr: ^[GDExtensionVariant_Size]u8,
	value: ^[GDExtensionVariant_Size]u8,
) {
	push_name_data: [8]u8
	ffi.string_name_new_with_latin1_chars(
		cast(ffi.UninitializedStringNamePtr)&push_name_data[0],
		cstring("push_back"),
		true,
	)
	push_name := ffi.StringNamePtr(&push_name_data[0])

	err: ffi.CallError
	ret: [GDExtensionVariant_Size]u8
	args := [1]ffi.ConstVariantPtr{cast(ffi.ConstVariantPtr)&value[0]}
	ffi.variant_call(
		cast(ffi.VariantPtr)&arr[0],
		push_name,
		&args[0],
		1,
		cast(ffi.UninitializedVariantPtr)&ret[0],
		&err,
	)
}

array_size :: proc "contextless" (arr: ^[GDExtensionVariant_Size]u8) -> i64 {
	size_name_data: [8]u8
	ffi.string_name_new_with_latin1_chars(
		cast(ffi.UninitializedStringNamePtr)&size_name_data[0],
		cstring("size"),
		true,
	)
	size_name := ffi.StringNamePtr(&size_name_data[0])

	ret: [GDExtensionVariant_Size]u8
	err: ffi.CallError
	ffi.variant_call(
		cast(ffi.VariantPtr)&arr[0],
		size_name,
		nil,
		0,
		cast(ffi.VariantPtr)&ret[0],
		&err,
	)
	dest: i64
	to_ctor := ffi.get_variant_to_type_constructor(.Int)
	to_ctor(cast(ffi.UninitializedTypePtr)&dest, cast(ffi.VariantPtr)&ret[0])
	return dest
}

// ---- print() utility function ----

print_name_data: [8]u8
print_name := ffi.StringNamePtr(&print_name_data[0])
print_hash: i64 = 2648703342

print_init :: proc() {
	ffi.string_name_new_with_latin1_chars(
		cast(ffi.UninitializedStringNamePtr)&print_name_data[0],
		cstring("print"),
		true,
	)
}

print :: proc "contextless" (args: ..ffi.TypePtr) {
	func := ffi.variant_get_ptr_utility_function(print_name, print_hash)
	if func == nil {return}
	ffi.call_utility_function_ptr_no_ret(func, ..args)
}
