// Code generated by bindgen from thirdparty/gdextension_interface.json. DO NOT EDIT.

package godot_core

/**
 * Gets the Godot version that the GDExtension was loaded into.
 * @since 4.1
 * @deprecated since 4.5 — use get_godot_version2
 */
get_godot_version: ExtensionInterfaceGetGodotVersion

/**
 * Gets the Godot version that the GDExtension was loaded into.
 * @since 4.5
 */
get_godot_version2: ExtensionInterfaceGetGodotVersion2

/**
 * Allocates memory.
 * @since 4.1
 * @deprecated since 4.6 — use mem_alloc2
 */
mem_alloc: ExtensionInterfaceMemAlloc

/**
 * Reallocates memory.
 * @since 4.1
 * @deprecated since 4.6 — use mem_realloc2
 */
mem_realloc: ExtensionInterfaceMemRealloc

/**
 * Frees memory.
 * @since 4.1
 * @deprecated since 4.6 — use mem_free2
 */
mem_free: ExtensionInterfaceMemFree

/**
 * Allocates memory.
 * @since 4.6
 */
mem_alloc2: ExtensionInterfaceMemAlloc2

/**
 * Reallocates memory.
 * @since 4.6
 */
mem_realloc2: ExtensionInterfaceMemRealloc2

/**
 * Frees memory.
 * @since 4.6
 */
mem_free2: ExtensionInterfaceMemFree2

/**
 * Logs an error to Godot's built-in debugger and to the OS terminal.
 * @since 4.1
 */
print_error: ExtensionInterfacePrintError

/**
 * Logs an error with a message to Godot's built-in debugger and to the OS terminal.
 * @since 4.1
 */
print_error_with_message: ExtensionInterfacePrintErrorWithMessage

/**
 * Logs a warning to Godot's built-in debugger and to the OS terminal.
 * @since 4.1
 */
print_warning: ExtensionInterfacePrintWarning

/**
 * Logs a warning with a message to Godot's built-in debugger and to the OS terminal.
 * @since 4.1
 */
print_warning_with_message: ExtensionInterfacePrintWarningWithMessage

/**
 * Logs a script error to Godot's built-in debugger and to the OS terminal.
 * @since 4.1
 */
print_script_error: ExtensionInterfacePrintScriptError

/**
 * Logs a script error with a message to Godot's built-in debugger and to the OS terminal.
 * @since 4.1
 */
print_script_error_with_message: ExtensionInterfacePrintScriptErrorWithMessage

/**
 * Gets the size of a native struct (ex. ObjectID) in bytes.
 * @since 4.1
 */
get_native_struct_size: ExtensionInterfaceGetNativeStructSize

/**
 * Copies one Variant into a another.
 * @since 4.1
 */
variant_new_copy: ExtensionInterfaceVariantNewCopy

/**
 * Creates a new Variant containing nil.
 * @since 4.1
 */
variant_new_nil: ExtensionInterfaceVariantNewNil

/**
 * Destroys a Variant.
 * @since 4.1
 */
variant_destroy: ExtensionInterfaceVariantDestroy

/**
 * Calls a method on a Variant.
 * @since 4.1
 */
variant_call: ExtensionInterfaceVariantCall

/**
 * Calls a static method on a Variant.
 * @since 4.1
 */
variant_call_static: ExtensionInterfaceVariantCallStatic

/**
 * Evaluate an operator on two Variants.
 * @since 4.1
 */
variant_evaluate: ExtensionInterfaceVariantEvaluate

/**
 * Sets a key on a Variant to a value.
 * @since 4.1
 */
variant_set: ExtensionInterfaceVariantSet

/**
 * Sets a named key on a Variant to a value.
 * @since 4.1
 */
variant_set_named: ExtensionInterfaceVariantSetNamed

/**
 * Sets a keyed property on a Variant to a value.
 * @since 4.1
 */
variant_set_keyed: ExtensionInterfaceVariantSetKeyed

/**
 * Sets an index on a Variant to a value.
 * @since 4.1
 */
variant_set_indexed: ExtensionInterfaceVariantSetIndexed

/**
 * Gets the value of a key from a Variant.
 * @since 4.1
 */
variant_get: ExtensionInterfaceVariantGet

/**
 * Gets the value of a named key from a Variant.
 * @since 4.1
 */
variant_get_named: ExtensionInterfaceVariantGetNamed

/**
 * Gets the value of a keyed property from a Variant.
 * @since 4.1
 */
variant_get_keyed: ExtensionInterfaceVariantGetKeyed

/**
 * Gets the value of an index from a Variant.
 * @since 4.1
 */
variant_get_indexed: ExtensionInterfaceVariantGetIndexed

/**
 * Initializes an iterator over a Variant.
 * @since 4.1
 */
variant_iter_init: ExtensionInterfaceVariantIterInit

/**
 * Gets the next value for an iterator over a Variant.
 * @since 4.1
 */
variant_iter_next: ExtensionInterfaceVariantIterNext

/**
 * Gets the next value for an iterator over a Variant.
 * @since 4.1
 */
variant_iter_get: ExtensionInterfaceVariantIterGet

/**
 * Gets the hash of a Variant.
 * @since 4.1
 */
variant_hash: ExtensionInterfaceVariantHash

/**
 * Gets the recursive hash of a Variant.
 * @since 4.1
 */
variant_recursive_hash: ExtensionInterfaceVariantRecursiveHash

/**
 * Compares two Variants by their hash.
 * @since 4.1
 */
variant_hash_compare: ExtensionInterfaceVariantHashCompare

/**
 * Converts a Variant to a boolean.
 * @since 4.1
 */
variant_booleanize: ExtensionInterfaceVariantBooleanize

/**
 * Duplicates a Variant.
 * @since 4.1
 */
variant_duplicate: ExtensionInterfaceVariantDuplicate

/**
 * Converts a Variant to a string.
 * @since 4.1
 */
variant_stringify: ExtensionInterfaceVariantStringify

/**
 * Gets the type of a Variant.
 * @since 4.1
 */
variant_get_type: ExtensionInterfaceVariantGetType

/**
 * Checks if a Variant has the given method.
 * @since 4.1
 */
variant_has_method: ExtensionInterfaceVariantHasMethod

/**
 * Checks if a type of Variant has the given member.
 * @since 4.1
 */
variant_has_member: ExtensionInterfaceVariantHasMember

/**
 * Checks if a Variant has a key.
 * @since 4.1
 */
variant_has_key: ExtensionInterfaceVariantHasKey

/**
 * Gets the object instance ID from a variant of type GDEXTENSION_VARIANT_TYPE_OBJECT.
 * If the variant isn't of type GDEXTENSION_VARIANT_TYPE_OBJECT, then zero will be returned.
 * The instance ID will be returned even if the object is no longer valid - use `object_get_instance_by_id()` to check if the object is still valid.
 * @since 4.4
 */
variant_get_object_instance_id: ExtensionInterfaceVariantGetObjectInstanceId

/**
 * Gets the name of a Variant type.
 * @since 4.1
 */
variant_get_type_name: ExtensionInterfaceVariantGetTypeName

/**
 * Gets the Variant type by name.
 * @since 4.7
 */
variant_get_type_by_name: ExtensionInterfaceVariantGetTypeByName

/**
 * Checks if Variants can be converted from one type to another.
 * @since 4.1
 */
variant_can_convert: ExtensionInterfaceVariantCanConvert

/**
 * Checks if Variant can be converted from one type to another using stricter rules.
 * @since 4.1
 */
variant_can_convert_strict: ExtensionInterfaceVariantCanConvertStrict

/**
 * Gets a pointer to a function that can create a Variant of the given type from a raw value.
 * @since 4.1
 */
get_variant_from_type_constructor: ExtensionInterfaceGetVariantFromTypeConstructor

/**
 * Gets a pointer to a function that can get the raw value from a Variant of the given type.
 * @since 4.1
 */
get_variant_to_type_constructor: ExtensionInterfaceGetVariantToTypeConstructor

/**
 * Provides a function pointer for retrieving a pointer to a variant's internal value.
 * Access to a variant's internal value can be used to modify it in-place, or to retrieve its value without the overhead of variant conversion functions.
 * It is recommended to cache the getter for all variant types in a function table to avoid retrieval overhead upon use.
 * 
 * Each function assumes the variant's type has already been determined and matches the function.
 * Invoking the function with a variant of a mismatched type has undefined behavior, and may lead to a segmentation fault.
 * @since 4.4
 */
variant_get_ptr_internal_getter: ExtensionInterfaceVariantGetPtrInternalGetter

/**
 * Gets a pointer to a function that can evaluate the given Variant operator on the given Variant types.
 * @since 4.1
 */
variant_get_ptr_operator_evaluator: ExtensionInterfaceVariantGetPtrOperatorEvaluator

/**
 * Gets a pointer to a function that can call a builtin method on a type of Variant.
 * @since 4.1
 */
variant_get_ptr_builtin_method: ExtensionInterfaceVariantGetPtrBuiltinMethod

/**
 * Gets a pointer to a function that can call one of the constructors for a type of Variant.
 * @since 4.1
 */
variant_get_ptr_constructor: ExtensionInterfaceVariantGetPtrConstructor

/**
 * Gets a pointer to a function than can call the destructor for a type of Variant.
 * @since 4.1
 */
variant_get_ptr_destructor: ExtensionInterfaceVariantGetPtrDestructor

/**
 * Constructs a Variant of the given type, using the first constructor that matches the given arguments.
 * @since 4.1
 */
variant_construct: ExtensionInterfaceVariantConstruct

/**
 * Gets a pointer to a function that can call a member's setter on the given Variant type.
 * @since 4.1
 */
variant_get_ptr_setter: ExtensionInterfaceVariantGetPtrSetter

/**
 * Gets a pointer to a function that can call a member's getter on the given Variant type.
 * @since 4.1
 */
variant_get_ptr_getter: ExtensionInterfaceVariantGetPtrGetter

/**
 * Gets a pointer to a function that can set an index on the given Variant type.
 * @since 4.1
 */
variant_get_ptr_indexed_setter: ExtensionInterfaceVariantGetPtrIndexedSetter

/**
 * Gets a pointer to a function that can get an index on the given Variant type.
 * @since 4.1
 */
variant_get_ptr_indexed_getter: ExtensionInterfaceVariantGetPtrIndexedGetter

/**
 * Gets a pointer to a function that can set a key on the given Variant type.
 * @since 4.1
 */
variant_get_ptr_keyed_setter: ExtensionInterfaceVariantGetPtrKeyedSetter

/**
 * Gets a pointer to a function that can get a key on the given Variant type.
 * @since 4.1
 */
variant_get_ptr_keyed_getter: ExtensionInterfaceVariantGetPtrKeyedGetter

/**
 * Gets a pointer to a function that can check a key on the given Variant type.
 * @since 4.1
 */
variant_get_ptr_keyed_checker: ExtensionInterfaceVariantGetPtrKeyedChecker

/**
 * Gets the value of a constant from the given Variant type.
 * @since 4.1
 */
variant_get_constant_value: ExtensionInterfaceVariantGetConstantValue

/**
 * Gets a pointer to a function that can call a Variant utility function.
 * @since 4.1
 */
variant_get_ptr_utility_function: ExtensionInterfaceVariantGetPtrUtilityFunction

/**
 * Creates a String from a Latin-1 encoded C string.
 * @since 4.1
 */
string_new_with_latin1_chars: ExtensionInterfaceStringNewWithLatin1Chars

/**
 * Creates a String from a UTF-8 encoded C string.
 * @since 4.1
 */
string_new_with_utf8_chars: ExtensionInterfaceStringNewWithUtf8Chars

/**
 * Creates a String from a UTF-16 encoded C string.
 * @since 4.1
 */
string_new_with_utf16_chars: ExtensionInterfaceStringNewWithUtf16Chars

/**
 * Creates a String from a UTF-32 encoded C string.
 * @since 4.1
 */
string_new_with_utf32_chars: ExtensionInterfaceStringNewWithUtf32Chars

/**
 * Creates a String from a wide C string.
 * @since 4.1
 */
string_new_with_wide_chars: ExtensionInterfaceStringNewWithWideChars

/**
 * Creates a String from a Latin-1 encoded C string with the given length.
 * @since 4.1
 */
string_new_with_latin1_chars_and_len: ExtensionInterfaceStringNewWithLatin1CharsAndLen

/**
 * Creates a String from a UTF-8 encoded C string with the given length.
 * @since 4.1
 * @deprecated since 4.3 — use string_new_with_utf8_chars_and_len2
 */
string_new_with_utf8_chars_and_len: ExtensionInterfaceStringNewWithUtf8CharsAndLen

/**
 * Creates a String from a UTF-8 encoded C string with the given length.
 * @since 4.3
 */
string_new_with_utf8_chars_and_len2: ExtensionInterfaceStringNewWithUtf8CharsAndLen2

/**
 * Creates a String from a UTF-16 encoded C string with the given length.
 * @since 4.1
 * @deprecated since 4.3 — use string_new_with_utf16_chars_and_len2
 */
string_new_with_utf16_chars_and_len: ExtensionInterfaceStringNewWithUtf16CharsAndLen

/**
 * Creates a String from a UTF-16 encoded C string with the given length.
 * @since 4.3
 */
string_new_with_utf16_chars_and_len2: ExtensionInterfaceStringNewWithUtf16CharsAndLen2

/**
 * Creates a String from a UTF-32 encoded C string with the given length.
 * @since 4.1
 */
string_new_with_utf32_chars_and_len: ExtensionInterfaceStringNewWithUtf32CharsAndLen

/**
 * Creates a String from a wide C string with the given length.
 * @since 4.1
 */
string_new_with_wide_chars_and_len: ExtensionInterfaceStringNewWithWideCharsAndLen

/**
 * Converts a String to a Latin-1 encoded C string.
 * It doesn't write a null terminator.
 * @since 4.1
 */
string_to_latin1_chars: ExtensionInterfaceStringToLatin1Chars

/**
 * Converts a String to a UTF-8 encoded C string.
 * It doesn't write a null terminator.
 * @since 4.1
 */
string_to_utf8_chars: ExtensionInterfaceStringToUtf8Chars

/**
 * Converts a String to a UTF-16 encoded C string.
 * It doesn't write a null terminator.
 * @since 4.1
 */
string_to_utf16_chars: ExtensionInterfaceStringToUtf16Chars

/**
 * Converts a String to a UTF-32 encoded C string.
 * It doesn't write a null terminator.
 * @since 4.1
 */
string_to_utf32_chars: ExtensionInterfaceStringToUtf32Chars

/**
 * Converts a String to a wide C string.
 * It doesn't write a null terminator.
 * @since 4.1
 */
string_to_wide_chars: ExtensionInterfaceStringToWideChars

/**
 * Gets a pointer to the character at the given index from a String.
 * @since 4.1
 */
string_operator_index: ExtensionInterfaceStringOperatorIndex

/**
 * Gets a const pointer to the character at the given index from a String.
 * @since 4.1
 */
string_operator_index_const: ExtensionInterfaceStringOperatorIndexConst

/**
 * Appends another String to a String.
 * @since 4.1
 */
string_operator_plus_eq_string: ExtensionInterfaceStringOperatorPlusEqString

/**
 * Appends a character to a String.
 * @since 4.1
 */
string_operator_plus_eq_char: ExtensionInterfaceStringOperatorPlusEqChar

/**
 * Appends a Latin-1 encoded C string to a String.
 * @since 4.1
 */
string_operator_plus_eq_cstr: ExtensionInterfaceStringOperatorPlusEqCstr

/**
 * Appends a wide C string to a String.
 * @since 4.1
 */
string_operator_plus_eq_wcstr: ExtensionInterfaceStringOperatorPlusEqWcstr

/**
 * Appends a UTF-32 encoded C string to a String.
 * @since 4.1
 */
string_operator_plus_eq_c32str: ExtensionInterfaceStringOperatorPlusEqC32str

/**
 * Resizes the underlying string data to the given number of characters.
 * Space needs to be allocated for the null terminating character ('\0') which
 * also must be added manually, in order for all string functions to work correctly.
 * 
 * Warning: This is an error-prone operation - only use it if there's no other
 * efficient way to accomplish your goal.
 * @since 4.2
 */
string_resize: ExtensionInterfaceStringResize

/**
 * Creates a StringName from a Latin-1 encoded C string.
 * If `p_is_static` is true, then:
 * - The StringName will reuse the `p_contents` buffer instead of copying it.
 * - You must guarantee that the buffer remains valid for the duration of the application (e.g. string literal).
 * - You must not call a destructor for this StringName. Incrementing the initial reference once should achieve this.
 * 
 * `p_is_static` is purely an optimization and can easily introduce undefined behavior if used wrong. In case of doubt, set it to false.
 * @since 4.2
 */
string_name_new_with_latin1_chars: ExtensionInterfaceStringNameNewWithLatin1Chars

/**
 * Creates a StringName from a UTF-8 encoded C string.
 * @since 4.2
 */
string_name_new_with_utf8_chars: ExtensionInterfaceStringNameNewWithUtf8Chars

/**
 * Creates a StringName from a UTF-8 encoded string with a given number of characters.
 * @since 4.2
 */
string_name_new_with_utf8_chars_and_len: ExtensionInterfaceStringNameNewWithUtf8CharsAndLen

/**
 * Opens a raw XML buffer on an XMLParser instance.
 * @since 4.1
 */
xml_parser_open_buffer: ExtensionInterfaceXmlParserOpenBuffer

/**
 * Stores the given buffer using an instance of FileAccess.
 * @since 4.1
 */
file_access_store_buffer: ExtensionInterfaceFileAccessStoreBuffer

/**
 * Reads the next p_length bytes into the given buffer using an instance of FileAccess.
 * @since 4.1
 */
file_access_get_buffer: ExtensionInterfaceFileAccessGetBuffer

/**
 * Returns writable pointer to internal Image buffer.
 * @since 4.3
 */
image_ptrw: ExtensionInterfaceImagePtrw

/**
 * Returns read only pointer to internal Image buffer.
 * @since 4.3
 */
image_ptr: ExtensionInterfaceImagePtr

/**
 * Adds a group task to an instance of WorkerThreadPool.
 * @since 4.1
 */
worker_thread_pool_add_native_group_task: ExtensionInterfaceWorkerThreadPoolAddNativeGroupTask

/**
 * Adds a task to an instance of WorkerThreadPool.
 * @since 4.1
 */
worker_thread_pool_add_native_task: ExtensionInterfaceWorkerThreadPoolAddNativeTask

/**
 * Gets a pointer to a byte in a PackedByteArray.
 * @since 4.1
 */
packed_byte_array_operator_index: ExtensionInterfacePackedByteArrayOperatorIndex

/**
 * Gets a const pointer to a byte in a PackedByteArray.
 * @since 4.1
 */
packed_byte_array_operator_index_const: ExtensionInterfacePackedByteArrayOperatorIndexConst

/**
 * Gets a pointer to a 32-bit float in a PackedFloat32Array.
 * @since 4.1
 */
packed_float32_array_operator_index: ExtensionInterfacePackedFloat32ArrayOperatorIndex

/**
 * Gets a const pointer to a 32-bit float in a PackedFloat32Array.
 * @since 4.1
 */
packed_float32_array_operator_index_const: ExtensionInterfacePackedFloat32ArrayOperatorIndexConst

/**
 * Gets a pointer to a 64-bit float in a PackedFloat64Array.
 * @since 4.1
 */
packed_float64_array_operator_index: ExtensionInterfacePackedFloat64ArrayOperatorIndex

/**
 * Gets a const pointer to a 64-bit float in a PackedFloat64Array.
 * @since 4.1
 */
packed_float64_array_operator_index_const: ExtensionInterfacePackedFloat64ArrayOperatorIndexConst

/**
 * Gets a pointer to a 32-bit integer in a PackedInt32Array.
 * @since 4.1
 */
packed_int32_array_operator_index: ExtensionInterfacePackedInt32ArrayOperatorIndex

/**
 * Gets a const pointer to a 32-bit integer in a PackedInt32Array.
 * @since 4.1
 */
packed_int32_array_operator_index_const: ExtensionInterfacePackedInt32ArrayOperatorIndexConst

/**
 * Gets a pointer to a 64-bit integer in a PackedInt64Array.
 * @since 4.1
 */
packed_int64_array_operator_index: ExtensionInterfacePackedInt64ArrayOperatorIndex

/**
 * Gets a const pointer to a 64-bit integer in a PackedInt64Array.
 * @since 4.1
 */
packed_int64_array_operator_index_const: ExtensionInterfacePackedInt64ArrayOperatorIndexConst

/**
 * Gets a pointer to a string in a PackedStringArray.
 * @since 4.1
 */
packed_string_array_operator_index: ExtensionInterfacePackedStringArrayOperatorIndex

/**
 * Gets a const pointer to a string in a PackedStringArray.
 * @since 4.1
 */
packed_string_array_operator_index_const: ExtensionInterfacePackedStringArrayOperatorIndexConst

/**
 * Gets a pointer to a Vector2 in a PackedVector2Array.
 * @since 4.1
 */
packed_vector2_array_operator_index: ExtensionInterfacePackedVector2ArrayOperatorIndex

/**
 * Gets a const pointer to a Vector2 in a PackedVector2Array.
 * @since 4.1
 */
packed_vector2_array_operator_index_const: ExtensionInterfacePackedVector2ArrayOperatorIndexConst

/**
 * Gets a pointer to a Vector3 in a PackedVector3Array.
 * @since 4.1
 */
packed_vector3_array_operator_index: ExtensionInterfacePackedVector3ArrayOperatorIndex

/**
 * Gets a const pointer to a Vector3 in a PackedVector3Array.
 * @since 4.1
 */
packed_vector3_array_operator_index_const: ExtensionInterfacePackedVector3ArrayOperatorIndexConst

/**
 * Gets a pointer to a Vector4 in a PackedVector4Array.
 * @since 4.3
 */
packed_vector4_array_operator_index: ExtensionInterfacePackedVector4ArrayOperatorIndex

/**
 * Gets a const pointer to a Vector4 in a PackedVector4Array.
 * @since 4.3
 */
packed_vector4_array_operator_index_const: ExtensionInterfacePackedVector4ArrayOperatorIndexConst

/**
 * Gets a pointer to a color in a PackedColorArray.
 * @since 4.1
 */
packed_color_array_operator_index: ExtensionInterfacePackedColorArrayOperatorIndex

/**
 * Gets a const pointer to a color in a PackedColorArray.
 * @since 4.1
 */
packed_color_array_operator_index_const: ExtensionInterfacePackedColorArrayOperatorIndexConst

/**
 * Gets a pointer to a Variant in an Array.
 * @since 4.1
 */
array_operator_index: ExtensionInterfaceArrayOperatorIndex

/**
 * Gets a const pointer to a Variant in an Array.
 * @since 4.1
 */
array_operator_index_const: ExtensionInterfaceArrayOperatorIndexConst

/**
 * Sets an Array to be a reference to another Array object.
 * @since 4.1
 * @deprecated since 4.5
 */
array_ref: ExtensionInterfaceArrayRef

/**
 * Makes an Array into a typed Array.
 * @since 4.1
 */
array_set_typed: ExtensionInterfaceArraySetTyped

/**
 * Gets a pointer to a Variant in a Dictionary with the given key.
 * @since 4.1
 */
dictionary_operator_index: ExtensionInterfaceDictionaryOperatorIndex

/**
 * Gets a const pointer to a Variant in a Dictionary with the given key.
 * @since 4.1
 */
dictionary_operator_index_const: ExtensionInterfaceDictionaryOperatorIndexConst

/**
 * Makes a Dictionary into a typed Dictionary.
 * @since 4.4
 */
dictionary_set_typed: ExtensionInterfaceDictionarySetTyped

/**
 * Calls a method on an Object.
 * @since 4.1
 */
object_method_bind_call: ExtensionInterfaceObjectMethodBindCall

/**
 * Calls a method on an Object (using a "ptrcall").
 * @since 4.1
 */
object_method_bind_ptrcall: ExtensionInterfaceObjectMethodBindPtrcall

/**
 * Destroys an Object.
 * @since 4.1
 */
object_destroy: ExtensionInterfaceObjectDestroy

/**
 * Gets a global singleton by name.
 * @since 4.1
 */
global_get_singleton: ExtensionInterfaceGlobalGetSingleton

/**
 * Gets a pointer representing an Object's instance binding.
 * @since 4.1
 */
object_get_instance_binding: ExtensionInterfaceObjectGetInstanceBinding

/**
 * Sets an Object's instance binding.
 * @since 4.1
 */
object_set_instance_binding: ExtensionInterfaceObjectSetInstanceBinding

/**
 * Free an Object's instance binding.
 * @since 4.2
 */
object_free_instance_binding: ExtensionInterfaceObjectFreeInstanceBinding

/**
 * Sets an extension class instance on a Object.
 * `p_classname` should be a registered extension class and should extend the `p_o` Object's class.
 * @since 4.1
 */
object_set_instance: ExtensionInterfaceObjectSetInstance

/**
 * Gets the class name of an Object.
 * If the GDExtension wraps the Godot object in an abstraction specific to its class, this is the
 * function that should be used to determine which wrapper to use.
 * @since 4.1
 */
object_get_class_name: ExtensionInterfaceObjectGetClassName

/**
 * Casts an Object to a different type.
 * @since 4.1
 * @deprecated since 4.7
 */
object_cast_to: ExtensionInterfaceObjectCastTo

/**
 * Gets an Object by its instance ID.
 * @since 4.1
 */
object_get_instance_from_id: ExtensionInterfaceObjectGetInstanceFromId

/**
 * Gets the instance ID from an Object.
 * @since 4.1
 */
object_get_instance_id: ExtensionInterfaceObjectGetInstanceId

/**
 * Checks if this object has a script with the given method.
 * @since 4.3
 */
object_has_script_method: ExtensionInterfaceObjectHasScriptMethod

/**
 * Call the given script method on this object.
 * @since 4.3
 */
object_call_script_method: ExtensionInterfaceObjectCallScriptMethod

/**
 * Gets the Object from a reference.
 * @since 4.1
 */
ref_get_object: ExtensionInterfaceRefGetObject

/**
 * Sets the Object referred to by a reference.
 * @since 4.1
 */
ref_set_object: ExtensionInterfaceRefSetObject

/**
 * Creates a script instance that contains the given info and instance data.
 * @since 4.1
 * @deprecated since 4.2 — use script_instance_create3
 */
script_instance_create: ExtensionInterfaceScriptInstanceCreate

/**
 * Creates a script instance that contains the given info and instance data.
 * @since 4.2
 * @deprecated since 4.3 — use script_instance_create3
 */
script_instance_create2: ExtensionInterfaceScriptInstanceCreate2

/**
 * Creates a script instance that contains the given info and instance data.
 * @since 4.3
 */
script_instance_create3: ExtensionInterfaceScriptInstanceCreate3

/**
 * Creates a placeholder script instance for a given script and instance.
 * This interface is optional as a custom placeholder could also be created with script_instance_create().
 * @since 4.2
 */
placeholder_script_instance_create: ExtensionInterfacePlaceholderScriptInstanceCreate

/**
 * Updates a placeholder script instance with the given properties and values.
 * The passed in placeholder must be an instance of PlaceHolderScriptInstance
 * such as the one returned by placeholder_script_instance_create().
 * @since 4.2
 */
placeholder_script_instance_update: ExtensionInterfacePlaceholderScriptInstanceUpdate

/**
 * Get the script instance data attached to this object.
 * @since 4.2
 */
object_get_script_instance: ExtensionInterfaceObjectGetScriptInstance

/**
 * Set the script instance data attached to this object.
 * @since 4.5
 */
object_set_script_instance: ExtensionInterfaceObjectSetScriptInstance

/**
 * Creates a custom Callable object from a function pointer.
 * Provided struct can be safely freed once the function returns.
 * @since 4.2
 * @deprecated since 4.3 — use callable_custom_create2
 */
callable_custom_create: ExtensionInterfaceCallableCustomCreate

/**
 * Creates a custom Callable object from a function pointer.
 * Provided struct can be safely freed once the function returns.
 * @since 4.3
 */
callable_custom_create2: ExtensionInterfaceCallableCustomCreate2

/**
 * Retrieves the userdata pointer from a custom Callable.
 * If the Callable is not a custom Callable or the token does not match the one provided to callable_custom_create() via GDExtensionCallableCustomInfo then NULL will be returned.
 * @since 4.2
 */
callable_custom_get_userdata: ExtensionInterfaceCallableCustomGetUserdata

/**
 * Constructs an Object of the requested class.
 * The passed class must be a built-in godot class, or an already-registered extension class. In both cases, object_set_instance() should be called to fully initialize the object.
 * @since 4.1
 * @deprecated since 4.4 — use classdb_construct_object3
 */
classdb_construct_object: ExtensionInterfaceClassdbConstructObject

/**
 * Constructs an Object of the requested class.
 * The passed class must be a built-in godot class, or an already-registered extension class. In both cases, object_set_instance() should be called to fully initialize the object.
 * 
 * "NOTIFICATION_POSTINITIALIZE" must be sent after construction.
 * @since 4.4
 * @deprecated since 4.7 — use classdb_construct_object3
 */
classdb_construct_object2: ExtensionInterfaceClassdbConstructObject2

/**
 * Constructs an Object of the requested class.
 * The passed class must be a built-in godot class, or an already-registered extension class. In both cases, object_set_instance() should be called to fully initialize the object.
 * If the type is a subtype of RefCounted, it already has a refcount of 1. The caller must take ownership the refcount and is responsible for decrementing it again when the object is no longer needed.
 * 
 * "NOTIFICATION_POSTINITIALIZE" must be sent after construction.
 * @since 4.7
 */
classdb_construct_object3: ExtensionInterfaceClassdbConstructObject3

/**
 * Gets a pointer to the MethodBind in ClassDB for the given class, method and hash.
 * @since 4.1
 */
classdb_get_method_bind: ExtensionInterfaceClassdbGetMethodBind

/**
 * Gets a pointer uniquely identifying the given built-in class in the ClassDB.
 * @since 4.1
 * @deprecated since 4.7
 */
classdb_get_class_tag: ExtensionInterfaceClassdbGetClassTag

/**
 * Registers an extension class in the ClassDB.
 * Provided struct can be safely freed once the function returns.
 * @since 4.1
 * @deprecated since 4.2 — use classdb_register_extension_class6
 */
classdb_register_extension_class: ExtensionInterfaceClassdbRegisterExtensionClass

/**
 * Registers an extension class in the ClassDB.
 * Provided struct can be safely freed once the function returns.
 * @since 4.2
 * @deprecated since 4.3 — use classdb_register_extension_class6
 */
classdb_register_extension_class2: ExtensionInterfaceClassdbRegisterExtensionClass2

/**
 * Registers an extension class in the ClassDB.
 * Provided struct can be safely freed once the function returns.
 * @since 4.3
 * @deprecated since 4.4 — use classdb_register_extension_class6
 */
classdb_register_extension_class3: ExtensionInterfaceClassdbRegisterExtensionClass3

/**
 * Registers an extension class in the ClassDB.
 * Provided struct can be safely freed once the function returns.
 * @since 4.4
 * @deprecated since 4.5 — use classdb_register_extension_class6
 */
classdb_register_extension_class4: ExtensionInterfaceClassdbRegisterExtensionClass4

/**
 * Registers an extension class in the ClassDB.
 * Provided struct can be safely freed once the function returns.
 * @since 4.5
 * @deprecated since 4.7 — use classdb_register_extension_class6
 */
classdb_register_extension_class5: ExtensionInterfaceClassdbRegisterExtensionClass5

/**
 * Registers an extension class in the ClassDB.
 * Provided struct can be safely freed once the function returns.
 * @since 4.7
 */
classdb_register_extension_class6: ExtensionInterfaceClassdbRegisterExtensionClass6

/**
 * Registers a method on an extension class in the ClassDB.
 * Provided struct can be safely freed once the function returns.
 * @since 4.1
 */
classdb_register_extension_class_method: ExtensionInterfaceClassdbRegisterExtensionClassMethod

/**
 * Registers a virtual method on an extension class in ClassDB, that can be implemented by scripts or other extensions.
 * Provided struct can be safely freed once the function returns.
 * @since 4.3
 */
classdb_register_extension_class_virtual_method: ExtensionInterfaceClassdbRegisterExtensionClassVirtualMethod

/**
 * Registers an integer constant on an extension class in the ClassDB.
 * Note about registering bitfield values (if p_is_bitfield is true): even though p_constant_value is signed, language bindings are
 * advised to treat bitfields as uint64_t, since this is generally clearer and can prevent mistakes like using -1 for setting all bits.
 * Language APIs should thus provide an abstraction that registers bitfields (uint64_t) separately from regular constants (int64_t).
 * @since 4.1
 */
classdb_register_extension_class_integer_constant: ExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant

/**
 * Registers a property on an extension class in the ClassDB.
 * Provided struct can be safely freed once the function returns.
 * @since 4.1
 */
classdb_register_extension_class_property: ExtensionInterfaceClassdbRegisterExtensionClassProperty

/**
 * Registers an indexed property on an extension class in the ClassDB.
 * Provided struct can be safely freed once the function returns.
 * @since 4.2
 */
classdb_register_extension_class_property_indexed: ExtensionInterfaceClassdbRegisterExtensionClassPropertyIndexed

/**
 * Registers a property group on an extension class in the ClassDB.
 * @since 4.1
 */
classdb_register_extension_class_property_group: ExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup

/**
 * Registers a property subgroup on an extension class in the ClassDB.
 * @since 4.1
 */
classdb_register_extension_class_property_subgroup: ExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup

/**
 * Registers a signal on an extension class in the ClassDB.
 * Provided structs can be safely freed once the function returns.
 * @since 4.1
 */
classdb_register_extension_class_signal: ExtensionInterfaceClassdbRegisterExtensionClassSignal

/**
 * Unregisters an extension class in the ClassDB.
 * Unregistering a parent class before a class that inherits it will result in failure. Inheritors must be unregistered first.
 * @since 4.1
 */
classdb_unregister_extension_class: ExtensionInterfaceClassdbUnregisterExtensionClass

/**
 * Gets the path to the current GDExtension library.
 * @since 4.1
 */
get_library_path: ExtensionInterfaceGetLibraryPath

/**
 * Adds an editor plugin.
 * It's safe to call during initialization.
 * @since 4.1
 */
editor_add_plugin: ExtensionInterfaceEditorAddPlugin

/**
 * Removes an editor plugin.
 * @since 4.1
 */
editor_remove_plugin: ExtensionInterfaceEditorRemovePlugin

/**
 * Loads new XML-formatted documentation data in the editor.
 * The provided pointer can be immediately freed once the function returns.
 * @since 4.3
 */
editor_help_load_xml_from_utf8_chars: ExtensionInterfaceEditorHelpLoadXmlFromUtf8Chars

/**
 * Loads new XML-formatted documentation data in the editor.
 * The provided pointer can be immediately freed once the function returns.
 * @since 4.3
 */
editor_help_load_xml_from_utf8_chars_and_len: ExtensionInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen

/**
 * Registers a callback that Godot can call to get the list of all classes (from ClassDB) that may be used by the calling GDExtension.
 * This is used by the editor to generate a build profile (in "Tools" > "Engine Compilation Configuration Editor..." > "Detect from project"),
 * in order to recompile Godot with only the classes used.
 * In the provided callback, the GDExtension should provide the list of classes that _may_ be used statically, thus the time of invocation shouldn't matter.
 * If a GDExtension doesn't register a callback, Godot will assume that it could be using any classes.
 * @since 4.5
 */
editor_register_get_classes_used_callback: ExtensionInterfaceEditorRegisterGetClassesUsedCallback

/**
 * Registers callbacks to be called at different phases of the main loop.
 * @since 4.5
 */
register_main_loop_callbacks: ExtensionInterfaceRegisterMainLoopCallbacks

// The library handle Godot passed to the entry point. Set by init().
library: GDExtensionClassLibraryPtr

// Resolves every interface function pointer from the host Godot instance.
// MUST be called exactly once, from the library entry point, before any other
// binding is used.
init :: proc "contextless" (
    p_library: GDExtensionClassLibraryPtr,
    p_get_proc_address: GDExtensionInterfaceGetProcAddress,
) {
    library = p_library
    get_godot_version = cast(ExtensionInterfaceGetGodotVersion)p_get_proc_address("get_godot_version")
    get_godot_version2 = cast(ExtensionInterfaceGetGodotVersion2)p_get_proc_address("get_godot_version2")
    mem_alloc = cast(ExtensionInterfaceMemAlloc)p_get_proc_address("mem_alloc")
    mem_realloc = cast(ExtensionInterfaceMemRealloc)p_get_proc_address("mem_realloc")
    mem_free = cast(ExtensionInterfaceMemFree)p_get_proc_address("mem_free")
    mem_alloc2 = cast(ExtensionInterfaceMemAlloc2)p_get_proc_address("mem_alloc2")
    mem_realloc2 = cast(ExtensionInterfaceMemRealloc2)p_get_proc_address("mem_realloc2")
    mem_free2 = cast(ExtensionInterfaceMemFree2)p_get_proc_address("mem_free2")
    print_error = cast(ExtensionInterfacePrintError)p_get_proc_address("print_error")
    print_error_with_message = cast(ExtensionInterfacePrintErrorWithMessage)p_get_proc_address("print_error_with_message")
    print_warning = cast(ExtensionInterfacePrintWarning)p_get_proc_address("print_warning")
    print_warning_with_message = cast(ExtensionInterfacePrintWarningWithMessage)p_get_proc_address("print_warning_with_message")
    print_script_error = cast(ExtensionInterfacePrintScriptError)p_get_proc_address("print_script_error")
    print_script_error_with_message = cast(ExtensionInterfacePrintScriptErrorWithMessage)p_get_proc_address("print_script_error_with_message")
    get_native_struct_size = cast(ExtensionInterfaceGetNativeStructSize)p_get_proc_address("get_native_struct_size")
    variant_new_copy = cast(ExtensionInterfaceVariantNewCopy)p_get_proc_address("variant_new_copy")
    variant_new_nil = cast(ExtensionInterfaceVariantNewNil)p_get_proc_address("variant_new_nil")
    variant_destroy = cast(ExtensionInterfaceVariantDestroy)p_get_proc_address("variant_destroy")
    variant_call = cast(ExtensionInterfaceVariantCall)p_get_proc_address("variant_call")
    variant_call_static = cast(ExtensionInterfaceVariantCallStatic)p_get_proc_address("variant_call_static")
    variant_evaluate = cast(ExtensionInterfaceVariantEvaluate)p_get_proc_address("variant_evaluate")
    variant_set = cast(ExtensionInterfaceVariantSet)p_get_proc_address("variant_set")
    variant_set_named = cast(ExtensionInterfaceVariantSetNamed)p_get_proc_address("variant_set_named")
    variant_set_keyed = cast(ExtensionInterfaceVariantSetKeyed)p_get_proc_address("variant_set_keyed")
    variant_set_indexed = cast(ExtensionInterfaceVariantSetIndexed)p_get_proc_address("variant_set_indexed")
    variant_get = cast(ExtensionInterfaceVariantGet)p_get_proc_address("variant_get")
    variant_get_named = cast(ExtensionInterfaceVariantGetNamed)p_get_proc_address("variant_get_named")
    variant_get_keyed = cast(ExtensionInterfaceVariantGetKeyed)p_get_proc_address("variant_get_keyed")
    variant_get_indexed = cast(ExtensionInterfaceVariantGetIndexed)p_get_proc_address("variant_get_indexed")
    variant_iter_init = cast(ExtensionInterfaceVariantIterInit)p_get_proc_address("variant_iter_init")
    variant_iter_next = cast(ExtensionInterfaceVariantIterNext)p_get_proc_address("variant_iter_next")
    variant_iter_get = cast(ExtensionInterfaceVariantIterGet)p_get_proc_address("variant_iter_get")
    variant_hash = cast(ExtensionInterfaceVariantHash)p_get_proc_address("variant_hash")
    variant_recursive_hash = cast(ExtensionInterfaceVariantRecursiveHash)p_get_proc_address("variant_recursive_hash")
    variant_hash_compare = cast(ExtensionInterfaceVariantHashCompare)p_get_proc_address("variant_hash_compare")
    variant_booleanize = cast(ExtensionInterfaceVariantBooleanize)p_get_proc_address("variant_booleanize")
    variant_duplicate = cast(ExtensionInterfaceVariantDuplicate)p_get_proc_address("variant_duplicate")
    variant_stringify = cast(ExtensionInterfaceVariantStringify)p_get_proc_address("variant_stringify")
    variant_get_type = cast(ExtensionInterfaceVariantGetType)p_get_proc_address("variant_get_type")
    variant_has_method = cast(ExtensionInterfaceVariantHasMethod)p_get_proc_address("variant_has_method")
    variant_has_member = cast(ExtensionInterfaceVariantHasMember)p_get_proc_address("variant_has_member")
    variant_has_key = cast(ExtensionInterfaceVariantHasKey)p_get_proc_address("variant_has_key")
    variant_get_object_instance_id = cast(ExtensionInterfaceVariantGetObjectInstanceId)p_get_proc_address("variant_get_object_instance_id")
    variant_get_type_name = cast(ExtensionInterfaceVariantGetTypeName)p_get_proc_address("variant_get_type_name")
    variant_get_type_by_name = cast(ExtensionInterfaceVariantGetTypeByName)p_get_proc_address("variant_get_type_by_name")
    variant_can_convert = cast(ExtensionInterfaceVariantCanConvert)p_get_proc_address("variant_can_convert")
    variant_can_convert_strict = cast(ExtensionInterfaceVariantCanConvertStrict)p_get_proc_address("variant_can_convert_strict")
    get_variant_from_type_constructor = cast(ExtensionInterfaceGetVariantFromTypeConstructor)p_get_proc_address("get_variant_from_type_constructor")
    get_variant_to_type_constructor = cast(ExtensionInterfaceGetVariantToTypeConstructor)p_get_proc_address("get_variant_to_type_constructor")
    variant_get_ptr_internal_getter = cast(ExtensionInterfaceVariantGetPtrInternalGetter)p_get_proc_address("variant_get_ptr_internal_getter")
    variant_get_ptr_operator_evaluator = cast(ExtensionInterfaceVariantGetPtrOperatorEvaluator)p_get_proc_address("variant_get_ptr_operator_evaluator")
    variant_get_ptr_builtin_method = cast(ExtensionInterfaceVariantGetPtrBuiltinMethod)p_get_proc_address("variant_get_ptr_builtin_method")
    variant_get_ptr_constructor = cast(ExtensionInterfaceVariantGetPtrConstructor)p_get_proc_address("variant_get_ptr_constructor")
    variant_get_ptr_destructor = cast(ExtensionInterfaceVariantGetPtrDestructor)p_get_proc_address("variant_get_ptr_destructor")
    variant_construct = cast(ExtensionInterfaceVariantConstruct)p_get_proc_address("variant_construct")
    variant_get_ptr_setter = cast(ExtensionInterfaceVariantGetPtrSetter)p_get_proc_address("variant_get_ptr_setter")
    variant_get_ptr_getter = cast(ExtensionInterfaceVariantGetPtrGetter)p_get_proc_address("variant_get_ptr_getter")
    variant_get_ptr_indexed_setter = cast(ExtensionInterfaceVariantGetPtrIndexedSetter)p_get_proc_address("variant_get_ptr_indexed_setter")
    variant_get_ptr_indexed_getter = cast(ExtensionInterfaceVariantGetPtrIndexedGetter)p_get_proc_address("variant_get_ptr_indexed_getter")
    variant_get_ptr_keyed_setter = cast(ExtensionInterfaceVariantGetPtrKeyedSetter)p_get_proc_address("variant_get_ptr_keyed_setter")
    variant_get_ptr_keyed_getter = cast(ExtensionInterfaceVariantGetPtrKeyedGetter)p_get_proc_address("variant_get_ptr_keyed_getter")
    variant_get_ptr_keyed_checker = cast(ExtensionInterfaceVariantGetPtrKeyedChecker)p_get_proc_address("variant_get_ptr_keyed_checker")
    variant_get_constant_value = cast(ExtensionInterfaceVariantGetConstantValue)p_get_proc_address("variant_get_constant_value")
    variant_get_ptr_utility_function = cast(ExtensionInterfaceVariantGetPtrUtilityFunction)p_get_proc_address("variant_get_ptr_utility_function")
    string_new_with_latin1_chars = cast(ExtensionInterfaceStringNewWithLatin1Chars)p_get_proc_address("string_new_with_latin1_chars")
    string_new_with_utf8_chars = cast(ExtensionInterfaceStringNewWithUtf8Chars)p_get_proc_address("string_new_with_utf8_chars")
    string_new_with_utf16_chars = cast(ExtensionInterfaceStringNewWithUtf16Chars)p_get_proc_address("string_new_with_utf16_chars")
    string_new_with_utf32_chars = cast(ExtensionInterfaceStringNewWithUtf32Chars)p_get_proc_address("string_new_with_utf32_chars")
    string_new_with_wide_chars = cast(ExtensionInterfaceStringNewWithWideChars)p_get_proc_address("string_new_with_wide_chars")
    string_new_with_latin1_chars_and_len = cast(ExtensionInterfaceStringNewWithLatin1CharsAndLen)p_get_proc_address("string_new_with_latin1_chars_and_len")
    string_new_with_utf8_chars_and_len = cast(ExtensionInterfaceStringNewWithUtf8CharsAndLen)p_get_proc_address("string_new_with_utf8_chars_and_len")
    string_new_with_utf8_chars_and_len2 = cast(ExtensionInterfaceStringNewWithUtf8CharsAndLen2)p_get_proc_address("string_new_with_utf8_chars_and_len2")
    string_new_with_utf16_chars_and_len = cast(ExtensionInterfaceStringNewWithUtf16CharsAndLen)p_get_proc_address("string_new_with_utf16_chars_and_len")
    string_new_with_utf16_chars_and_len2 = cast(ExtensionInterfaceStringNewWithUtf16CharsAndLen2)p_get_proc_address("string_new_with_utf16_chars_and_len2")
    string_new_with_utf32_chars_and_len = cast(ExtensionInterfaceStringNewWithUtf32CharsAndLen)p_get_proc_address("string_new_with_utf32_chars_and_len")
    string_new_with_wide_chars_and_len = cast(ExtensionInterfaceStringNewWithWideCharsAndLen)p_get_proc_address("string_new_with_wide_chars_and_len")
    string_to_latin1_chars = cast(ExtensionInterfaceStringToLatin1Chars)p_get_proc_address("string_to_latin1_chars")
    string_to_utf8_chars = cast(ExtensionInterfaceStringToUtf8Chars)p_get_proc_address("string_to_utf8_chars")
    string_to_utf16_chars = cast(ExtensionInterfaceStringToUtf16Chars)p_get_proc_address("string_to_utf16_chars")
    string_to_utf32_chars = cast(ExtensionInterfaceStringToUtf32Chars)p_get_proc_address("string_to_utf32_chars")
    string_to_wide_chars = cast(ExtensionInterfaceStringToWideChars)p_get_proc_address("string_to_wide_chars")
    string_operator_index = cast(ExtensionInterfaceStringOperatorIndex)p_get_proc_address("string_operator_index")
    string_operator_index_const = cast(ExtensionInterfaceStringOperatorIndexConst)p_get_proc_address("string_operator_index_const")
    string_operator_plus_eq_string = cast(ExtensionInterfaceStringOperatorPlusEqString)p_get_proc_address("string_operator_plus_eq_string")
    string_operator_plus_eq_char = cast(ExtensionInterfaceStringOperatorPlusEqChar)p_get_proc_address("string_operator_plus_eq_char")
    string_operator_plus_eq_cstr = cast(ExtensionInterfaceStringOperatorPlusEqCstr)p_get_proc_address("string_operator_plus_eq_cstr")
    string_operator_plus_eq_wcstr = cast(ExtensionInterfaceStringOperatorPlusEqWcstr)p_get_proc_address("string_operator_plus_eq_wcstr")
    string_operator_plus_eq_c32str = cast(ExtensionInterfaceStringOperatorPlusEqC32str)p_get_proc_address("string_operator_plus_eq_c32str")
    string_resize = cast(ExtensionInterfaceStringResize)p_get_proc_address("string_resize")
    string_name_new_with_latin1_chars = cast(ExtensionInterfaceStringNameNewWithLatin1Chars)p_get_proc_address("string_name_new_with_latin1_chars")
    string_name_new_with_utf8_chars = cast(ExtensionInterfaceStringNameNewWithUtf8Chars)p_get_proc_address("string_name_new_with_utf8_chars")
    string_name_new_with_utf8_chars_and_len = cast(ExtensionInterfaceStringNameNewWithUtf8CharsAndLen)p_get_proc_address("string_name_new_with_utf8_chars_and_len")
    xml_parser_open_buffer = cast(ExtensionInterfaceXmlParserOpenBuffer)p_get_proc_address("xml_parser_open_buffer")
    file_access_store_buffer = cast(ExtensionInterfaceFileAccessStoreBuffer)p_get_proc_address("file_access_store_buffer")
    file_access_get_buffer = cast(ExtensionInterfaceFileAccessGetBuffer)p_get_proc_address("file_access_get_buffer")
    image_ptrw = cast(ExtensionInterfaceImagePtrw)p_get_proc_address("image_ptrw")
    image_ptr = cast(ExtensionInterfaceImagePtr)p_get_proc_address("image_ptr")
    worker_thread_pool_add_native_group_task = cast(ExtensionInterfaceWorkerThreadPoolAddNativeGroupTask)p_get_proc_address("worker_thread_pool_add_native_group_task")
    worker_thread_pool_add_native_task = cast(ExtensionInterfaceWorkerThreadPoolAddNativeTask)p_get_proc_address("worker_thread_pool_add_native_task")
    packed_byte_array_operator_index = cast(ExtensionInterfacePackedByteArrayOperatorIndex)p_get_proc_address("packed_byte_array_operator_index")
    packed_byte_array_operator_index_const = cast(ExtensionInterfacePackedByteArrayOperatorIndexConst)p_get_proc_address("packed_byte_array_operator_index_const")
    packed_float32_array_operator_index = cast(ExtensionInterfacePackedFloat32ArrayOperatorIndex)p_get_proc_address("packed_float32_array_operator_index")
    packed_float32_array_operator_index_const = cast(ExtensionInterfacePackedFloat32ArrayOperatorIndexConst)p_get_proc_address("packed_float32_array_operator_index_const")
    packed_float64_array_operator_index = cast(ExtensionInterfacePackedFloat64ArrayOperatorIndex)p_get_proc_address("packed_float64_array_operator_index")
    packed_float64_array_operator_index_const = cast(ExtensionInterfacePackedFloat64ArrayOperatorIndexConst)p_get_proc_address("packed_float64_array_operator_index_const")
    packed_int32_array_operator_index = cast(ExtensionInterfacePackedInt32ArrayOperatorIndex)p_get_proc_address("packed_int32_array_operator_index")
    packed_int32_array_operator_index_const = cast(ExtensionInterfacePackedInt32ArrayOperatorIndexConst)p_get_proc_address("packed_int32_array_operator_index_const")
    packed_int64_array_operator_index = cast(ExtensionInterfacePackedInt64ArrayOperatorIndex)p_get_proc_address("packed_int64_array_operator_index")
    packed_int64_array_operator_index_const = cast(ExtensionInterfacePackedInt64ArrayOperatorIndexConst)p_get_proc_address("packed_int64_array_operator_index_const")
    packed_string_array_operator_index = cast(ExtensionInterfacePackedStringArrayOperatorIndex)p_get_proc_address("packed_string_array_operator_index")
    packed_string_array_operator_index_const = cast(ExtensionInterfacePackedStringArrayOperatorIndexConst)p_get_proc_address("packed_string_array_operator_index_const")
    packed_vector2_array_operator_index = cast(ExtensionInterfacePackedVector2ArrayOperatorIndex)p_get_proc_address("packed_vector2_array_operator_index")
    packed_vector2_array_operator_index_const = cast(ExtensionInterfacePackedVector2ArrayOperatorIndexConst)p_get_proc_address("packed_vector2_array_operator_index_const")
    packed_vector3_array_operator_index = cast(ExtensionInterfacePackedVector3ArrayOperatorIndex)p_get_proc_address("packed_vector3_array_operator_index")
    packed_vector3_array_operator_index_const = cast(ExtensionInterfacePackedVector3ArrayOperatorIndexConst)p_get_proc_address("packed_vector3_array_operator_index_const")
    packed_vector4_array_operator_index = cast(ExtensionInterfacePackedVector4ArrayOperatorIndex)p_get_proc_address("packed_vector4_array_operator_index")
    packed_vector4_array_operator_index_const = cast(ExtensionInterfacePackedVector4ArrayOperatorIndexConst)p_get_proc_address("packed_vector4_array_operator_index_const")
    packed_color_array_operator_index = cast(ExtensionInterfacePackedColorArrayOperatorIndex)p_get_proc_address("packed_color_array_operator_index")
    packed_color_array_operator_index_const = cast(ExtensionInterfacePackedColorArrayOperatorIndexConst)p_get_proc_address("packed_color_array_operator_index_const")
    array_operator_index = cast(ExtensionInterfaceArrayOperatorIndex)p_get_proc_address("array_operator_index")
    array_operator_index_const = cast(ExtensionInterfaceArrayOperatorIndexConst)p_get_proc_address("array_operator_index_const")
    array_ref = cast(ExtensionInterfaceArrayRef)p_get_proc_address("array_ref")
    array_set_typed = cast(ExtensionInterfaceArraySetTyped)p_get_proc_address("array_set_typed")
    dictionary_operator_index = cast(ExtensionInterfaceDictionaryOperatorIndex)p_get_proc_address("dictionary_operator_index")
    dictionary_operator_index_const = cast(ExtensionInterfaceDictionaryOperatorIndexConst)p_get_proc_address("dictionary_operator_index_const")
    dictionary_set_typed = cast(ExtensionInterfaceDictionarySetTyped)p_get_proc_address("dictionary_set_typed")
    object_method_bind_call = cast(ExtensionInterfaceObjectMethodBindCall)p_get_proc_address("object_method_bind_call")
    object_method_bind_ptrcall = cast(ExtensionInterfaceObjectMethodBindPtrcall)p_get_proc_address("object_method_bind_ptrcall")
    object_destroy = cast(ExtensionInterfaceObjectDestroy)p_get_proc_address("object_destroy")
    global_get_singleton = cast(ExtensionInterfaceGlobalGetSingleton)p_get_proc_address("global_get_singleton")
    object_get_instance_binding = cast(ExtensionInterfaceObjectGetInstanceBinding)p_get_proc_address("object_get_instance_binding")
    object_set_instance_binding = cast(ExtensionInterfaceObjectSetInstanceBinding)p_get_proc_address("object_set_instance_binding")
    object_free_instance_binding = cast(ExtensionInterfaceObjectFreeInstanceBinding)p_get_proc_address("object_free_instance_binding")
    object_set_instance = cast(ExtensionInterfaceObjectSetInstance)p_get_proc_address("object_set_instance")
    object_get_class_name = cast(ExtensionInterfaceObjectGetClassName)p_get_proc_address("object_get_class_name")
    object_cast_to = cast(ExtensionInterfaceObjectCastTo)p_get_proc_address("object_cast_to")
    object_get_instance_from_id = cast(ExtensionInterfaceObjectGetInstanceFromId)p_get_proc_address("object_get_instance_from_id")
    object_get_instance_id = cast(ExtensionInterfaceObjectGetInstanceId)p_get_proc_address("object_get_instance_id")
    object_has_script_method = cast(ExtensionInterfaceObjectHasScriptMethod)p_get_proc_address("object_has_script_method")
    object_call_script_method = cast(ExtensionInterfaceObjectCallScriptMethod)p_get_proc_address("object_call_script_method")
    ref_get_object = cast(ExtensionInterfaceRefGetObject)p_get_proc_address("ref_get_object")
    ref_set_object = cast(ExtensionInterfaceRefSetObject)p_get_proc_address("ref_set_object")
    script_instance_create = cast(ExtensionInterfaceScriptInstanceCreate)p_get_proc_address("script_instance_create")
    script_instance_create2 = cast(ExtensionInterfaceScriptInstanceCreate2)p_get_proc_address("script_instance_create2")
    script_instance_create3 = cast(ExtensionInterfaceScriptInstanceCreate3)p_get_proc_address("script_instance_create3")
    placeholder_script_instance_create = cast(ExtensionInterfacePlaceholderScriptInstanceCreate)p_get_proc_address("placeholder_script_instance_create")
    placeholder_script_instance_update = cast(ExtensionInterfacePlaceholderScriptInstanceUpdate)p_get_proc_address("placeholder_script_instance_update")
    object_get_script_instance = cast(ExtensionInterfaceObjectGetScriptInstance)p_get_proc_address("object_get_script_instance")
    object_set_script_instance = cast(ExtensionInterfaceObjectSetScriptInstance)p_get_proc_address("object_set_script_instance")
    callable_custom_create = cast(ExtensionInterfaceCallableCustomCreate)p_get_proc_address("callable_custom_create")
    callable_custom_create2 = cast(ExtensionInterfaceCallableCustomCreate2)p_get_proc_address("callable_custom_create2")
    callable_custom_get_userdata = cast(ExtensionInterfaceCallableCustomGetUserdata)p_get_proc_address("callable_custom_get_userdata")
    classdb_construct_object = cast(ExtensionInterfaceClassdbConstructObject)p_get_proc_address("classdb_construct_object")
    classdb_construct_object2 = cast(ExtensionInterfaceClassdbConstructObject2)p_get_proc_address("classdb_construct_object2")
    classdb_construct_object3 = cast(ExtensionInterfaceClassdbConstructObject3)p_get_proc_address("classdb_construct_object3")
    classdb_get_method_bind = cast(ExtensionInterfaceClassdbGetMethodBind)p_get_proc_address("classdb_get_method_bind")
    classdb_get_class_tag = cast(ExtensionInterfaceClassdbGetClassTag)p_get_proc_address("classdb_get_class_tag")
    classdb_register_extension_class = cast(ExtensionInterfaceClassdbRegisterExtensionClass)p_get_proc_address("classdb_register_extension_class")
    classdb_register_extension_class2 = cast(ExtensionInterfaceClassdbRegisterExtensionClass2)p_get_proc_address("classdb_register_extension_class2")
    classdb_register_extension_class3 = cast(ExtensionInterfaceClassdbRegisterExtensionClass3)p_get_proc_address("classdb_register_extension_class3")
    classdb_register_extension_class4 = cast(ExtensionInterfaceClassdbRegisterExtensionClass4)p_get_proc_address("classdb_register_extension_class4")
    classdb_register_extension_class5 = cast(ExtensionInterfaceClassdbRegisterExtensionClass5)p_get_proc_address("classdb_register_extension_class5")
    classdb_register_extension_class6 = cast(ExtensionInterfaceClassdbRegisterExtensionClass6)p_get_proc_address("classdb_register_extension_class6")
    classdb_register_extension_class_method = cast(ExtensionInterfaceClassdbRegisterExtensionClassMethod)p_get_proc_address("classdb_register_extension_class_method")
    classdb_register_extension_class_virtual_method = cast(ExtensionInterfaceClassdbRegisterExtensionClassVirtualMethod)p_get_proc_address("classdb_register_extension_class_virtual_method")
    classdb_register_extension_class_integer_constant = cast(ExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant)p_get_proc_address("classdb_register_extension_class_integer_constant")
    classdb_register_extension_class_property = cast(ExtensionInterfaceClassdbRegisterExtensionClassProperty)p_get_proc_address("classdb_register_extension_class_property")
    classdb_register_extension_class_property_indexed = cast(ExtensionInterfaceClassdbRegisterExtensionClassPropertyIndexed)p_get_proc_address("classdb_register_extension_class_property_indexed")
    classdb_register_extension_class_property_group = cast(ExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup)p_get_proc_address("classdb_register_extension_class_property_group")
    classdb_register_extension_class_property_subgroup = cast(ExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup)p_get_proc_address("classdb_register_extension_class_property_subgroup")
    classdb_register_extension_class_signal = cast(ExtensionInterfaceClassdbRegisterExtensionClassSignal)p_get_proc_address("classdb_register_extension_class_signal")
    classdb_unregister_extension_class = cast(ExtensionInterfaceClassdbUnregisterExtensionClass)p_get_proc_address("classdb_unregister_extension_class")
    get_library_path = cast(ExtensionInterfaceGetLibraryPath)p_get_proc_address("get_library_path")
    editor_add_plugin = cast(ExtensionInterfaceEditorAddPlugin)p_get_proc_address("editor_add_plugin")
    editor_remove_plugin = cast(ExtensionInterfaceEditorRemovePlugin)p_get_proc_address("editor_remove_plugin")
    editor_help_load_xml_from_utf8_chars = cast(ExtensionInterfaceEditorHelpLoadXmlFromUtf8Chars)p_get_proc_address("editor_help_load_xml_from_utf8_chars")
    editor_help_load_xml_from_utf8_chars_and_len = cast(ExtensionInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen)p_get_proc_address("editor_help_load_xml_from_utf8_chars_and_len")
    editor_register_get_classes_used_callback = cast(ExtensionInterfaceEditorRegisterGetClassesUsedCallback)p_get_proc_address("editor_register_get_classes_used_callback")
    register_main_loop_callbacks = cast(ExtensionInterfaceRegisterMainLoopCallbacks)p_get_proc_address("register_main_loop_callbacks")
}
