// variant.odin -- Variant marshaling and utility-function wrappers.
// These are manual prototypes; eventually they will be generated by godot-codegen.
// https://docs.godotengine.org/fr/4.x/classes/class_variant.html
package godot_core


GDExtensionVariant_Size :: 24
GDExtensionString_Size :: 8
GDExtensionStringName_Size :: 8

// StringStorage is raw storage large enough for Godot's ABI String handle.
// Treat it as uninitialized until a string_init_* helper or Godot API has
// constructed a String in it.
StringStorage :: [GDExtensionString_Size]u8

// String is initialized Godot String storage. Every proc returning a String
// transfers ownership to the caller; destroy it with string_free when finished.
String :: distinct StringStorage

// string_ptr returns a mutable GDExtension pointer to initialized String storage.
string_ptr :: proc "contextless" (s: ^String) -> StringPtr {
	if s == nil do _trap_nil_godot_function()
	return cast(StringPtr)s
}

// const_string_ptr returns a read-only GDExtension pointer to initialized String storage.
const_string_ptr :: proc "contextless" (s: ^String) -> ConstStringPtr {
	if s == nil do _trap_nil_godot_function()
	return cast(ConstStringPtr)s
}

// uninitialized_string_ptr returns a GDExtension pointer to storage that Godot
// is about to initialize. Do not pass already-owned String storage here unless
// the called Godot API explicitly overwrites it without leaking.
uninitialized_string_ptr :: proc "contextless" (s: ^String) -> UninitializedStringPtr {
	if s == nil do _trap_nil_godot_function()
	return cast(UninitializedStringPtr)s
}

// string_init_utf8 constructs a Godot String from UTF-8 bytes. The input does
// not need to be null-terminated and is copied into Godot-owned storage.
string_init_utf8 :: proc "contextless" (dest: UninitializedStringPtr, value: string) {
	if string_new_with_utf8_chars_and_len2 == nil do _trap_nil_godot_function()
	if dest == nil do _trap_nil_godot_function()
	bytes := transmute([]u8)value
	if len(bytes) == 0 {
		written := string_new_with_utf8_chars_and_len2(dest, cstring(""), 0)
		if written < 0 do _trap_godot_call_error()
		return
	}
	written := string_new_with_utf8_chars_and_len2(
		dest,
		cast(cstring)raw_data(bytes),
		i64(len(bytes)),
	)
	if written < 0 do _trap_godot_call_error()
}

// string_from_utf8 returns an initialized Godot String; call string_free when done.
string_from_utf8 :: proc "contextless" (value: string) -> (result: String) {
	string_init_utf8(uninitialized_string_ptr(&result), value)
	return
}

// string_utf8_len returns the number of bytes needed to encode s as UTF-8. The
// result does not include a null terminator.
string_utf8_len :: proc "contextless" (s: ^String) -> int {
	if string_to_utf8_chars == nil do _trap_nil_godot_function()
	return int(string_to_utf8_chars(const_string_ptr(s), nil, 0))
}

// string_to_utf8 copies UTF-8 bytes into caller-provided storage and returns an
// Odin string view into that buffer. It does not write or require a terminator.
string_to_utf8 :: proc "contextless" (
	s: ^String,
	buffer: []u8,
) -> (
	value: string,
	ok: bool,
	needed: int,
) {
	byte_count := string_utf8_len(s)
	if byte_count > len(buffer) do return "", false, byte_count
	if byte_count > 0 do string_to_utf8_chars(const_string_ptr(s), raw_data(buffer), i64(byte_count))
	return string(buffer[:byte_count]), true, byte_count
}

string_free :: proc "contextless" (s: ^String) {
	destroy_builtin(.String, string_ptr(s))
}

// StringNameStorage is raw storage large enough for Godot's ABI StringName handle.
// Treat it as uninitialized until a string_name_init_* helper or Godot API has
// constructed a StringName in it.
StringNameStorage :: [GDExtensionStringName_Size]u8

// StringName is initialized, non-static Godot StringName storage. Every proc
// returning a StringName transfers ownership to the caller; destroy it with
// string_name_free when finished. Do not use string_name_free on StringNames
// constructed with Godot's static StringName optimization.
StringName :: distinct StringNameStorage

// string_name_ptr returns a mutable GDExtension pointer to initialized StringName storage.
string_name_ptr :: proc "contextless" (s: ^StringName) -> StringNamePtr {
	if s == nil do _trap_nil_godot_function()
	return cast(StringNamePtr)s
}

// const_string_name_ptr returns a read-only GDExtension pointer to initialized StringName storage.
const_string_name_ptr :: proc "contextless" (s: ^StringName) -> ConstStringNamePtr {
	if s == nil do _trap_nil_godot_function()
	return cast(ConstStringNamePtr)s
}

// uninitialized_string_name_ptr returns a GDExtension pointer to storage that
// Godot is about to initialize. Do not pass already-owned StringName storage
// here unless the called API explicitly overwrites it without leaking.
uninitialized_string_name_ptr :: proc "contextless" (
	s: ^StringName,
) -> UninitializedStringNamePtr {
	if s == nil do _trap_nil_godot_function()
	return cast(UninitializedStringNamePtr)s
}

// string_name_init_utf8_cstring constructs a non-static StringName from a
// null-terminated UTF-8 C string. The caller owns dest and must free it.
string_name_init_utf8_cstring :: proc "contextless" (
	dest: UninitializedStringNamePtr,
	value: cstring,
) {
	if string_name_new_with_utf8_chars == nil do _trap_nil_godot_function()
	if dest == nil || value == nil do _trap_nil_godot_function()
	string_name_new_with_utf8_chars(dest, value)
}

// string_name_from_utf8_cstring returns an initialized non-static StringName;
// call string_name_free when done.
string_name_from_utf8_cstring :: proc "contextless" (value: cstring) -> (result: StringName) {
	string_name_init_utf8_cstring(uninitialized_string_name_ptr(&result), value)
	return
}

string_name_free :: proc "contextless" (s: ^StringName) {
	destroy_builtin(.String_Name, string_name_ptr(s))
}

// StaticStringName is initialized Godot StringName storage using Godot's
// static-name optimization. The source C string must remain valid for the whole
// process, and StaticStringName values must never be destroyed.
StaticStringName :: distinct StringNameStorage

// static_string_name_ptr returns a mutable GDExtension pointer to initialized
// static StringName storage.
static_string_name_ptr :: proc "contextless" (s: ^StaticStringName) -> StringNamePtr {
	if s == nil do _trap_nil_godot_function()
	return cast(StringNamePtr)s
}

// const_static_string_name_ptr returns a read-only GDExtension pointer to
// initialized static StringName storage.
const_static_string_name_ptr :: proc "contextless" (s: ^StaticStringName) -> ConstStringNamePtr {
	if s == nil do _trap_nil_godot_function()
	return cast(ConstStringNamePtr)s
}

// uninitialized_static_string_name_ptr returns a GDExtension pointer to storage
// that Godot is about to initialize as a static StringName.
uninitialized_static_string_name_ptr :: proc "contextless" (
	s: ^StaticStringName,
) -> UninitializedStringNamePtr {
	if s == nil do _trap_nil_godot_function()
	return cast(UninitializedStringNamePtr)s
}

// static_string_name_init_latin1_cstring constructs a static StringName from a
// process-lifetime Latin-1/ASCII C string literal. Never call string_name_free
// on storage initialized by this helper.
static_string_name_init_latin1_cstring :: proc "contextless" (
	dest: UninitializedStringNamePtr,
	value: cstring,
) {
	if string_name_new_with_latin1_chars == nil do _trap_nil_godot_function()
	if dest == nil || value == nil do _trap_nil_godot_function()
	string_name_new_with_latin1_chars(dest, value, true)
}

// VariantStorage is raw storage large enough for Godot's ABI Variant. Treat it
// as uninitialized until one of the variant_init_* helpers or Godot itself has
// constructed a Variant in it.
VariantStorage :: [GDExtensionVariant_Size]u8

// Variant is initialized Godot Variant storage. Every proc returning a Variant
// transfers ownership to the caller; destroy it with variant_free when finished.
Variant :: distinct VariantStorage

// variant_ptr returns a mutable GDExtension pointer to initialized Variant
// storage. Nil pointers trap instead of crossing the GDExtension boundary.
variant_ptr :: proc "contextless" (v: ^Variant) -> VariantPtr {
	if v == nil do _trap_nil_godot_function()
	return cast(VariantPtr)v
}

// const_variant_ptr returns a read-only GDExtension pointer to initialized
// Variant storage. Nil pointers trap instead of crossing the GDExtension boundary.
const_variant_ptr :: proc "contextless" (v: ^Variant) -> ConstVariantPtr {
	if v == nil do _trap_nil_godot_function()
	return cast(ConstVariantPtr)v
}

// uninitialized_variant_ptr returns a GDExtension pointer to storage that Godot
// is about to initialize. The caller must not pass already-owned Variant storage
// unless the called Godot API explicitly overwrites it without leaking.
uninitialized_variant_ptr :: proc "contextless" (v: ^Variant) -> UninitializedVariantPtr {
	if v == nil do _trap_nil_godot_function()
	return cast(UninitializedVariantPtr)v
}

// ---- Variant type inspection ----

variant_type :: proc "contextless" (v: ^Variant) -> VariantType {
	if variant_get_type == nil do _trap_nil_godot_function()
	return variant_get_type(const_variant_ptr(v))
}

variant_is_type :: proc "contextless" (v: ^Variant, type: VariantType) -> bool {
	return variant_type(v) == type
}

variant_is_nil :: proc "contextless" (v: ^Variant) -> bool {
	return variant_is_type(v, .Nil)
}

// ---- Variant construction ----

variant_init_nil :: proc "contextless" (dest: UninitializedVariantPtr) {
	if variant_new_nil == nil do _trap_nil_godot_function()
	if dest == nil do _trap_nil_godot_function()
	variant_new_nil(dest)
}

variant_nil :: proc "contextless" () -> (v: Variant) {
	variant_init_nil(uninitialized_variant_ptr(&v))
	return
}

variant_init_copy :: proc "contextless" (dest: UninitializedVariantPtr, src: ^Variant) {
	if variant_new_copy == nil do _trap_nil_godot_function()
	if dest == nil do _trap_nil_godot_function()
	variant_new_copy(dest, const_variant_ptr(src))
}

variant_copy :: proc "contextless" (src: ^Variant) -> (v: Variant) {
	variant_init_copy(uninitialized_variant_ptr(&v), src)
	return
}

variant_from_float :: proc "contextless" (x: f64) -> (v: Variant) {
	ctor := require_variant_from_type_constructor(.Float)
	_x := x
	ctor(uninitialized_variant_ptr(&v), cast(TypePtr)&_x)
	return
}

variant_from_string :: proc "contextless" (s: ^String) -> (v: Variant) {
	ctor := require_variant_from_type_constructor(.String)
	ctor(uninitialized_variant_ptr(&v), string_ptr(s))
	return
}

variant_from_string_name :: proc "contextless" (s: ^StringName) -> (v: Variant) {
	ctor := require_variant_from_type_constructor(.String_Name)
	ctor(uninitialized_variant_ptr(&v), string_name_ptr(s))
	return
}

variant_from_utf8 :: proc "contextless" (s: string) -> (v: Variant) {
	str := string_from_utf8(s)
	defer string_free(&str)
	return variant_from_string(&str)
}

variant_from_cstring :: proc "contextless" (s: cstring) -> (v: Variant) {
	if s == nil do _trap_nil_godot_function()
	str_data: [8]u8
	string_new_with_latin1_chars(cast(UninitializedStringPtr)&str_data[0], s)
	ctor := require_variant_from_type_constructor(.String)
	ctor(uninitialized_variant_ptr(&v), cast(TypePtr)&str_data[0])
	destroy_builtin(.String, cast(TypePtr)&str_data[0])
	return
}

variant_free :: proc "contextless" (v: ^Variant) {
	if variant_destroy == nil do _trap_nil_godot_function()
	variant_destroy(variant_ptr(v))
}

// Variant-returning calls initialize their return storage even for nil/void
// results. Destroy every initialized temporary Variant after extracting data from
// it. Generated wrappers should follow this same ownership rule.
variant_free_temp :: proc "contextless" (v: ^Variant) {
	variant_free(v)
}

variant_from_bool :: proc "contextless" (x: bool) -> (v: Variant) {
	ctor := require_variant_from_type_constructor(.Bool)
	_x := x
	ctor(uninitialized_variant_ptr(&v), cast(TypePtr)&_x)
	return
}

variant_from_int :: proc "contextless" (x: i64) -> (v: Variant) {
	ctor := require_variant_from_type_constructor(.Int)
	_x := x
	ctor(uninitialized_variant_ptr(&v), cast(TypePtr)&_x)
	return
}

// ---- Variant extraction ----

variant_to_float :: proc "contextless" (v: ^Variant) -> f64 {
	ctor := require_variant_to_type_constructor(.Float)
	ret: f64
	ctor(cast(UninitializedTypePtr)&ret, variant_ptr(v))
	return ret
}

variant_to_int :: proc "contextless" (v: ^Variant) -> i64 {
	ctor := require_variant_to_type_constructor(.Int)
	ret: i64
	ctor(cast(UninitializedTypePtr)&ret, variant_ptr(v))
	return ret
}

variant_to_bool :: proc "contextless" (v: ^Variant) -> bool {
	ctor := require_variant_to_type_constructor(.Bool)
	ret: bool
	ctor(cast(UninitializedTypePtr)&ret, variant_ptr(v))
	return ret
}

variant_to_string_storage :: proc "contextless" (dest: UninitializedStringPtr, v: ^Variant) {
	if dest == nil do _trap_nil_godot_function()
	ctor := require_variant_to_type_constructor(.String)
	ctor(dest, variant_ptr(v))
}

variant_to_string :: proc "contextless" (v: ^Variant) -> (result: String) {
	variant_to_string_storage(uninitialized_string_ptr(&result), v)
	return
}

variant_try_string :: proc "contextless" (v: ^Variant) -> (value: String, ok: bool) {
	if !variant_is_type(v, .String) do return String{}, false
	return variant_to_string(v), true
}

variant_to_string_name :: proc "contextless" (v: ^Variant) -> (result: StringName) {
	ctor := require_variant_to_type_constructor(.String_Name)
	ctor(uninitialized_string_name_ptr(&result), variant_ptr(v))
	return
}

variant_try_string_name :: proc "contextless" (v: ^Variant) -> (value: StringName, ok: bool) {
	if !variant_is_type(v, .String_Name) do return StringName{}, false
	return variant_to_string_name(v), true
}

variant_string_utf8_len :: proc "contextless" (v: ^Variant) -> (needed: int, ok: bool) {
	str, type_ok := variant_try_string(v)
	if !type_ok do return 0, false
	defer string_free(&str)
	return string_utf8_len(&str), true
}

variant_try_utf8 :: proc "contextless" (
	v: ^Variant,
	buffer: []u8,
) -> (
	value: string,
	ok: bool,
	needed: int,
) {
	byte_count, type_ok := variant_string_utf8_len(v)
	if !type_ok do return "", false, 0
	if byte_count > len(buffer) do return "", false, byte_count

	if byte_count > 0 {
		str := variant_to_string(v)
		defer string_free(&str)
		string_to_utf8_chars(const_string_ptr(&str), raw_data(buffer), i64(byte_count))
	}
	return string(buffer[:byte_count]), true, byte_count
}

variant_try_float :: proc "contextless" (v: ^Variant) -> (value: f64, ok: bool) {
	if !variant_is_type(v, .Float) do return 0, false
	return variant_to_float(v), true
}

variant_try_int :: proc "contextless" (v: ^Variant) -> (value: i64, ok: bool) {
	if !variant_is_type(v, .Int) do return 0, false
	return variant_to_int(v), true
}

variant_try_bool :: proc "contextless" (v: ^Variant) -> (value: bool, ok: bool) {
	if !variant_is_type(v, .Bool) do return false, false
	return variant_to_bool(v), true
}

// ---- Variant call errors ----

call_error_ok :: proc "contextless" (err: ^CallError) -> bool {
	if err == nil do _trap_nil_godot_function()
	return err.error == .Ok
}

require_call_ok :: proc "contextless" (err: ^CallError) {
	if !call_error_ok(err) do _trap_godot_call_error()
}

variant_construct_checked :: proc "contextless" (
	type: VariantType,
	dest: UninitializedVariantPtr,
	args: [^]ConstVariantPtr,
	arg_count: i32,
) -> (
	err: CallError,
) {
	if variant_construct == nil do _trap_nil_godot_function()
	if dest == nil do _trap_nil_godot_function()
	if arg_count < 0 do _trap_godot_call_error()
	if arg_count > 0 && args == nil do _trap_nil_godot_function()
	variant_construct(type, dest, args, arg_count, &err)
	return
}

variant_call_checked :: proc "contextless" (
	base: ^Variant,
	method: ConstStringNamePtr,
	args: [^]ConstVariantPtr,
	arg_count: i64,
	ret: UninitializedVariantPtr,
) -> (
	err: CallError,
) {
	if variant_call == nil do _trap_nil_godot_function()
	if method == nil do _trap_nil_godot_function()
	if ret == nil do _trap_nil_godot_function()
	if arg_count < 0 do _trap_godot_call_error()
	if arg_count > 0 && args == nil do _trap_nil_godot_function()
	variant_call(variant_ptr(base), method, args, arg_count, ret, &err)
	return
}

// ---- Array builtin ----

array_new :: proc "contextless" () -> (v: Variant) {
	err := variant_construct_checked(.Array, uninitialized_variant_ptr(&v), nil, 0)
	require_call_ok(&err)
	return
}

array_push :: proc "contextless" (arr: ^Variant, value: ^Variant) {
	push_name_data: StaticStringName
	static_string_name_init_latin1_cstring(
		uninitialized_static_string_name_ptr(&push_name_data),
		cstring("push_back"),
	)
	push_name := const_static_string_name_ptr(&push_name_data)

	ret: Variant
	args := [1]ConstVariantPtr{const_variant_ptr(value)}
	err := variant_call_checked(arr, push_name, &args[0], 1, uninitialized_variant_ptr(&ret))
	variant_free_temp(&ret)
	require_call_ok(&err)
}

array_size :: proc "contextless" (arr: ^Variant) -> i64 {
	size_name_data: StaticStringName
	static_string_name_init_latin1_cstring(
		uninitialized_static_string_name_ptr(&size_name_data),
		cstring("size"),
	)
	size_name := const_static_string_name_ptr(&size_name_data)

	ret: Variant
	err := variant_call_checked(arr, size_name, nil, 0, uninitialized_variant_ptr(&ret))
	if !call_error_ok(&err) {
		variant_free_temp(&ret)
		require_call_ok(&err)
	}
	dest: i64
	to_ctor := require_variant_to_type_constructor(.Int)
	to_ctor(cast(UninitializedTypePtr)&dest, variant_ptr(&ret))
	variant_free_temp(&ret)
	return dest
}

// ---- print() utility function ----

print_name_data: StaticStringName
print_hash: i64 = 2648703342

print_init :: proc() {
	static_string_name_init_latin1_cstring(
		uninitialized_static_string_name_ptr(&print_name_data),
		cstring("print"),
	)
}

print :: proc "contextless" (args: ..TypePtr) {
	func := require_utility_function(const_static_string_name_ptr(&print_name_data), print_hash)
	call_utility_function_ptr_no_ret(func, ..args)
}
