// variant.odin -- Variant marshaling and utility-function wrappers.
// These are manual prototypes; eventually they will be generated by godot-codegen.
// https://docs.godotengine.org/fr/4.x/classes/class_variant.html
package godot_core


GDExtensionVariant_Size :: 24

// ---- Variant construction ----

variant_from_float :: proc "contextless" (x: f64) -> (v: [GDExtensionVariant_Size]u8) {
	ctor := get_variant_from_type_constructor(.Float)
	_x := x
	ctor(cast(UninitializedVariantPtr)&v[0], cast(TypePtr)&_x)
	return
}

variant_from_cstring :: proc "contextless" (s: cstring) -> (v: [GDExtensionVariant_Size]u8) {
	str_data: [8]u8
	string_new_with_latin1_chars(cast(UninitializedStringPtr)&str_data[0], s)
	ctor := get_variant_from_type_constructor(.String)
	ctor(cast(UninitializedVariantPtr)&v[0], cast(TypePtr)&str_data[0])
	return
}

variant_free :: proc "contextless" (v: ^[GDExtensionVariant_Size]u8) {
	variant_destroy(cast(VariantPtr)&v[0])
}

variant_from_bool :: proc "contextless" (x: bool) -> (v: [GDExtensionVariant_Size]u8) {
	ctor := get_variant_from_type_constructor(.Bool)
	_x := x
	ctor(cast(UninitializedVariantPtr)&v[0], cast(TypePtr)&_x)
	return
}

variant_from_int :: proc "contextless" (x: i64) -> (v: [GDExtensionVariant_Size]u8) {
	ctor := get_variant_from_type_constructor(.Int)
	_x := x
	ctor(cast(UninitializedVariantPtr)&v[0], cast(TypePtr)&_x)
	return
}

// ---- Variant extraction ----

variant_to_float :: proc "contextless" (v: ^[GDExtensionVariant_Size]u8) -> f64 {
	ctor := get_variant_to_type_constructor(.Float)
	ret: f64
	ctor(cast(UninitializedTypePtr)&ret, cast(VariantPtr)&v[0])
	return ret
}

variant_to_int :: proc "contextless" (v: ^[GDExtensionVariant_Size]u8) -> i64 {
	ctor := get_variant_to_type_constructor(.Int)
	ret: i64
	ctor(cast(UninitializedTypePtr)&ret, cast(VariantPtr)&v[0])
	return ret
}

variant_to_bool :: proc "contextless" (v: ^[GDExtensionVariant_Size]u8) -> bool {
	ctor := get_variant_to_type_constructor(.Bool)
	ret: bool
	ctor(cast(UninitializedTypePtr)&ret, cast(VariantPtr)&v[0])
	return ret
}

// ---- Array builtin ----

array_new :: proc "contextless" () -> (v: [GDExtensionVariant_Size]u8) {
	err: CallError
	variant_construct(.Array, cast(UninitializedVariantPtr)&v[0], nil, 0, &err)
	return
}

array_push :: proc "contextless" (
	arr: ^[GDExtensionVariant_Size]u8,
	value: ^[GDExtensionVariant_Size]u8,
) {
	push_name_data: [8]u8
	string_name_new_with_latin1_chars(
		cast(UninitializedStringNamePtr)&push_name_data[0],
		cstring("push_back"),
		true,
	)
	push_name := StringNamePtr(&push_name_data[0])

	err: CallError
	ret: [GDExtensionVariant_Size]u8
	args := [1]ConstVariantPtr{cast(ConstVariantPtr)&value[0]}
	variant_call(
		cast(VariantPtr)&arr[0],
		push_name,
		&args[0],
		1,
		cast(UninitializedVariantPtr)&ret[0],
		&err,
	)
}

array_size :: proc "contextless" (arr: ^[GDExtensionVariant_Size]u8) -> i64 {
	size_name_data: [8]u8
	string_name_new_with_latin1_chars(
		cast(UninitializedStringNamePtr)&size_name_data[0],
		cstring("size"),
		true,
	)
	size_name := StringNamePtr(&size_name_data[0])

	ret: [GDExtensionVariant_Size]u8
	err: CallError
	variant_call(cast(VariantPtr)&arr[0], size_name, nil, 0, cast(VariantPtr)&ret[0], &err)
	dest: i64
	to_ctor := get_variant_to_type_constructor(.Int)
	to_ctor(cast(UninitializedTypePtr)&dest, cast(VariantPtr)&ret[0])
	return dest
}

// ---- print() utility function ----

print_name_data: [8]u8
print_name := StringNamePtr(&print_name_data[0])
print_hash: i64 = 2648703342

print_init :: proc() {
	string_name_new_with_latin1_chars(
		cast(UninitializedStringNamePtr)&print_name_data[0],
		cstring("print"),
		true,
	)
}

print :: proc "contextless" (args: ..TypePtr) {
	func := variant_get_ptr_utility_function(print_name, print_hash)
	if func == nil {return}
	call_utility_function_ptr_no_ret(func, ..args)
}
